/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { CmdString, DeepseekTestParams } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDeepseekTest = () => {
  /**
   * @summary 测试DeepSeek API
   */
  const deepseekTest = (params?: DeepseekTestParams) => {
    return customInstance<CmdString>({ url: `/api/test/deepseek`, method: 'GET', params });
  };
  return { deepseekTest };
};
export type DeepseekTestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDeepseekTest>['deepseekTest']>>
>;
