/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdString } from '../api.schemas';

export const getDeepseekTestResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getDeepseekTestMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.get('*/api/test/deepseek', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDeepseekTestResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getDeepseekTestMock = () => [getDeepseekTestMockHandler()];
