/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultGetRandomPhoneVO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getTool = () => {
  /**
   * @summary 获取随机中国手机号和身份证号
   */
  const getRandomPhone = () => {
    return customInstance<ResultGetRandomPhoneVO>({
      url: `/api/tool/getRandomPhone`,
      method: 'GET',
    });
  };
  return { getRandomPhone };
};
export type GetRandomPhoneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTool>['getRandomPhone']>>
>;
