/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { CallDeepSeekParams, ResultString } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDeepSeek = () => {
  /**
   * @summary 调用deepSeek
   */
  const callDeepSeek = (params: CallDeepSeekParams) => {
    return customInstance<ResultString>({ url: `/api/callDeepSeek`, method: 'GET', params });
  };
  return { callDeepSeek };
};
export type CallDeepSeekResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDeepSeek>['callDeepSeek']>>
>;
