/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultScanIdentifyResponseVO, ScanIdentifyRequestDTO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getScan = () => {
  /**
   * @summary 识别二维码类型
   */
  const identifyQRCode = (scanIdentifyRequestDTO: ScanIdentifyRequestDTO) => {
    return customInstance<ResultScanIdentifyResponseVO>({
      url: `/api/scan/identify`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: scanIdentifyRequestDTO,
    });
  };
  return { identifyQRCode };
};
export type IdentifyQRCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getScan>['identifyQRCode']>>
>;
