/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdScanIdentifyResponseDTO } from '../api.schemas';

export const getIdentifyQRCodeResponseMock = (
  overrideResponse: Partial<CmdScanIdentifyResponseDTO> = {},
): CmdScanIdentifyResponseDTO => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      type: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      url: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      fallbackUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getIdentifyQRCodeMockHandler = (
  overrideResponse?:
    | CmdScanIdentifyResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CmdScanIdentifyResponseDTO> | CmdScanIdentifyResponseDTO),
) => {
  return http.post('*/api/scan/identify', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getIdentifyQRCodeResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getScanMock = () => [getIdentifyQRCodeMockHandler()];
