/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  DevTask,
  ResultBoolean,
  ResultDevTask,
  ResultListDevTask,
  ResultListString,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getTask = () => {
  /**
   * @summary 新增
   */
  const saveRequirement = (devTask: DevTask) => {
    return customInstance<ResultBoolean>({
      url: `/api/task`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: devTask,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const getRequirementById = (id: string) => {
    return customInstance<ResultDevTask>({ url: `/api/task/${id}`, method: 'GET' });
  };
  /**
   * @summary 获取所有需求的名称
   */
  const getAllRequirementNames = () => {
    return customInstance<ResultListString>({ url: `/api/task/name-all`, method: 'GET' });
  };
  /**
   * @summary 获取当前用户的需求
   */
  const getCurrentUserRequirement = () => {
    return customInstance<ResultListDevTask>({ url: `/api/task/list`, method: 'GET' });
  };
  return { saveRequirement, getRequirementById, getAllRequirementNames, getCurrentUserRequirement };
};
export type SaveRequirementResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTask>['saveRequirement']>>
>;
export type GetRequirementByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTask>['getRequirementById']>>
>;
export type GetAllRequirementNamesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTask>['getAllRequirementNames']>>
>;
export type GetCurrentUserRequirementResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTask>['getCurrentUserRequirement']>>
>;
