/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  CmdBoolean,
  CmdDailyTaskEntity,
  CmdListDailyTaskEntity,
  DailyTaskEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDailyTask = () => {
  /**
   * @summary 更新
   */
  const dailyTaskUpdate = (dailyTaskEntity: DailyTaskEntity) => {
    return customInstance<CmdBoolean>({
      url: `/api/dailyTask`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: dailyTaskEntity,
    });
  };
  /**
   * @summary 新增
   */
  const dailyTaskCreate = (dailyTaskEntity: DailyTaskEntity) => {
    return customInstance<CmdBoolean>({
      url: `/api/dailyTask`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: dailyTaskEntity,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const dailyTaskGetById = (id: number) => {
    return customInstance<CmdDailyTaskEntity>({ url: `/api/dailyTask/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除
   */
  const dailyTaskDelete = (id: number) => {
    return customInstance<CmdBoolean>({ url: `/api/dailyTask/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取当前用户的任务
   */
  const dailyTaskMeTask = () => {
    return customInstance<CmdListDailyTaskEntity>({ url: `/api/dailyTask/list`, method: 'GET' });
  };
  return { dailyTaskUpdate, dailyTaskCreate, dailyTaskGetById, dailyTaskDelete, dailyTaskMeTask };
};
export type DailyTaskUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDailyTask>['dailyTaskUpdate']>>
>;
export type DailyTaskCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDailyTask>['dailyTaskCreate']>>
>;
export type DailyTaskGetByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDailyTask>['dailyTaskGetById']>>
>;
export type DailyTaskDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDailyTask>['dailyTaskDelete']>>
>;
export type DailyTaskMeTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDailyTask>['dailyTaskMeTask']>>
>;
