/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type {
  ResultBoolean,
  ResultDailyTaskEntity,
  ResultListDailyTaskEntity,
} from '../api.schemas';

export const getDailyTaskUpdateResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDailyTaskCreateResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDailyTaskGetByIdResponseMock = (
  overrideResponse: Partial<ResultDailyTaskEntity> = {},
): ResultDailyTaskEntity => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      title: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      content: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      status: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      priority: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      plannedStartTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      plannedEndTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      completedTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      remarks: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getDailyTaskDeleteByIdResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDailyTaskMeTaskResponseMock = (
  overrideResponse: Partial<ResultListDailyTaskEntity> = {},
): ResultListDailyTaskEntity => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      title: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      content: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      status: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      priority: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      plannedStartTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      plannedEndTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      completedTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      remarks: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDailyTaskUpdateMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.put('*/api/dailyTask', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskUpdateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskCreateMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.post('*/api/dailyTask', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskCreateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskGetByIdMockHandler = (
  overrideResponse?:
    | ResultDailyTaskEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultDailyTaskEntity> | ResultDailyTaskEntity),
) => {
  return http.get('*/api/dailyTask/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskGetByIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskDeleteByIdMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.delete('*/api/dailyTask/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskDeleteByIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskMeTaskMockHandler = (
  overrideResponse?:
    | ResultListDailyTaskEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultListDailyTaskEntity> | ResultListDailyTaskEntity),
) => {
  return http.get('*/api/dailyTask/list', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskMeTaskResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getDailyTaskMock = () => [
  getDailyTaskUpdateMockHandler(),
  getDailyTaskCreateMockHandler(),
  getDailyTaskGetByIdMockHandler(),
  getDailyTaskDeleteByIdMockHandler(),
  getDailyTaskMeTaskMockHandler(),
];
