/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdBoolean, CmdDailyTaskEntity, CmdListDailyTaskEntity } from '../api.schemas';

export const getDailyTaskUpdateResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDailyTaskCreateResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDailyTaskGetByIdResponseMock = (
  overrideResponse: Partial<CmdDailyTaskEntity> = {},
): CmdDailyTaskEntity => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      title: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      content: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      status: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      priority: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      plannedStartTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      plannedEndTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      completedTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      remarks: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getDailyTaskDeleteResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDailyTaskMeTaskResponseMock = (
  overrideResponse: Partial<CmdListDailyTaskEntity> = {},
): CmdListDailyTaskEntity => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      title: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      content: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      status: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      priority: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      plannedStartTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      plannedEndTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      completedTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      remarks: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDailyTaskUpdateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.put('*/api/dailyTask', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskUpdateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskCreateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.post('*/api/dailyTask', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskCreateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskGetByIdMockHandler = (
  overrideResponse?:
    | CmdDailyTaskEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdDailyTaskEntity> | CmdDailyTaskEntity),
) => {
  return http.get('*/api/dailyTask/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskGetByIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskDeleteMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.delete('*/api/dailyTask/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskDeleteResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDailyTaskMeTaskMockHandler = (
  overrideResponse?:
    | CmdListDailyTaskEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdListDailyTaskEntity> | CmdListDailyTaskEntity),
) => {
  return http.get('*/api/dailyTask/list', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDailyTaskMeTaskResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getDailyTaskMock = () => [
  getDailyTaskUpdateMockHandler(),
  getDailyTaskCreateMockHandler(),
  getDailyTaskGetByIdMockHandler(),
  getDailyTaskDeleteMockHandler(),
  getDailyTaskMeTaskMockHandler(),
];
