/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultGetRandomPhoneVO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getRandom = () => {
  const getRandomPhone = () => {
    return customInstance<ResultGetRandomPhoneVO>({
      url: `/api/random/random/getRandomPhone`,
      method: 'GET',
    });
  };
  return { getRandomPhone };
};
export type GetRandomPhoneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRandom>['getRandomPhone']>>
>;
