/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { ResultBoolean, ResultString, ResultUserLoginResponseDTO } from '../api.schemas';

export const getUpdatePasswordResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getRegisterResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getLoginResponseMock = (
  overrideResponse: Partial<ResultUserLoginResponseDTO> = {},
): ResultUserLoginResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      token: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      user: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          username: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          email: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          role: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          avatarUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
        },
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getSendVerifyCodeResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getGetVapidPublicKeyResponseMock = (
  overrideResponse: Partial<ResultString> = {},
): ResultString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getUpdatePasswordMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.put('*/api/auth/password', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUpdatePasswordResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getRegisterMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.post('*/api/auth/register', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getRegisterResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getLoginMockHandler = (
  overrideResponse?:
    | ResultUserLoginResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultUserLoginResponseDTO> | ResultUserLoginResponseDTO),
) => {
  return http.post('*/api/auth/login', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getLoginResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSendVerifyCodeMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.post('*/api/auth/code', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSendVerifyCodeResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetVapidPublicKeyMockHandler = (
  overrideResponse?:
    | ResultString
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultString> | ResultString),
) => {
  return http.get('*/api/auth/vapidPublicKey', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVapidPublicKeyResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getAuthMock = () => [
  getUpdatePasswordMockHandler(),
  getRegisterMockHandler(),
  getLoginMockHandler(),
  getSendVerifyCodeMockHandler(),
  getGetVapidPublicKeyMockHandler(),
];
