/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  AuthCodeParams,
  CmdString,
  CmdUserLoginResponseDTO,
  RegisterRequestDTO,
  UpdatePasswordRequestDTO,
  UserLoginRequestDTO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getAuth = () => {
  /**
   * @summary 忘记密码-修改密码
   */
  const authPassword = (updatePasswordRequestDTO: UpdatePasswordRequestDTO) => {
    return customInstance<CmdString>({
      url: `/api/auth/password`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updatePasswordRequestDTO,
    });
  };
  /**
   * @summary 注册
   */
  const authRegister = (registerRequestDTO: RegisterRequestDTO) => {
    return customInstance<CmdString>({
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequestDTO,
    });
  };
  /**
   * @summary 登录
   */
  const authLogin = (userLoginRequestDTO: UserLoginRequestDTO) => {
    return customInstance<CmdUserLoginResponseDTO>({
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userLoginRequestDTO,
    });
  };
  /**
   * @summary 获取VAPID公钥
   */
  const authVapidPublicKey = () => {
    return customInstance<CmdString>({ url: `/api/auth/vapidPublicKey`, method: 'GET' });
  };
  /**
   * @summary 获取验证码
   */
  const authCode = (params: AuthCodeParams) => {
    return customInstance<CmdString>({ url: `/api/auth/code`, method: 'GET', params });
  };
  return { authPassword, authRegister, authLogin, authVapidPublicKey, authCode };
};
export type AuthPasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['authPassword']>>
>;
export type AuthRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['authRegister']>>
>;
export type AuthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['authLogin']>>
>;
export type AuthVapidPublicKeyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['authVapidPublicKey']>>
>;
export type AuthCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['authCode']>>
>;
