/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  RegisterRequestDTO,
  ResultBoolean,
  ResultString,
  ResultUserLoginResponseDTO,
  UpdatePasswordRequestDTO,
  UserLoginRequestDTO,
  VerifyCodeRequestDTO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getAuth = () => {
  /**
   * @summary 忘记密码-修改密码
   */
  const updatePassword = (updatePasswordRequestDTO: UpdatePasswordRequestDTO) => {
    return customInstance<ResultBoolean>({
      url: `/api/auth/password`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updatePasswordRequestDTO,
    });
  };
  /**
   * @summary 注册
   */
  const register = (registerRequestDTO: RegisterRequestDTO) => {
    return customInstance<ResultBoolean>({
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequestDTO,
    });
  };
  /**
   * @summary 登录
   */
  const login = (userLoginRequestDTO: UserLoginRequestDTO) => {
    return customInstance<ResultUserLoginResponseDTO>({
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userLoginRequestDTO,
    });
  };
  /**
   * @summary 获取验证码
   */
  const sendVerifyCode = (verifyCodeRequestDTO: VerifyCodeRequestDTO) => {
    return customInstance<ResultBoolean>({
      url: `/api/auth/code`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: verifyCodeRequestDTO,
    });
  };
  /**
   * @summary 获取VAPID公钥
   */
  const getVapidPublicKey = () => {
    return customInstance<ResultString>({ url: `/api/auth/vapidPublicKey`, method: 'GET' });
  };
  return { updatePassword, register, login, sendVerifyCode, getVapidPublicKey };
};
export type UpdatePasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['updatePassword']>>
>;
export type RegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['register']>>
>;
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['login']>>>;
export type SendVerifyCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['sendVerifyCode']>>
>;
export type GetVapidPublicKeyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['getVapidPublicKey']>>
>;
