/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdString, CmdUserLoginResponseDTO } from '../api.schemas';

export const getAuthPasswordResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getAuthRegisterResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getAuthLoginResponseMock = (
  overrideResponse: Partial<CmdUserLoginResponseDTO> = {},
): CmdUserLoginResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      token: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      user: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          username: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          email: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          needResetPassword: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
          role: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          avatarUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
        },
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getAuthVapidPublicKeyResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getAuthCodeResponseMock = (overrideResponse: Partial<CmdString> = {}): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getAuthPasswordMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.put('*/api/auth/password', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthPasswordResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getAuthRegisterMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.post('*/api/auth/register', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthRegisterResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getAuthLoginMockHandler = (
  overrideResponse?:
    | CmdUserLoginResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CmdUserLoginResponseDTO> | CmdUserLoginResponseDTO),
) => {
  return http.post('*/api/auth/login', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthLoginResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getAuthVapidPublicKeyMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.get('*/api/auth/vapidPublicKey', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthVapidPublicKeyResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getAuthCodeMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.get('*/api/auth/code', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthCodeResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getAuthMock = () => [
  getAuthPasswordMockHandler(),
  getAuthRegisterMockHandler(),
  getAuthLoginMockHandler(),
  getAuthVapidPublicKeyMockHandler(),
  getAuthCodeMockHandler(),
];
