/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  LoginInParam,
  RegisterRequestDTO,
  ResultBoolean,
  ResultLoginVO,
  ResultString,
  ResultUserLoginVO,
  UpdatePasswordRequestDTO,
  VerifyCodeRequestDTO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getAuth = () => {
  /**
   * @summary 注册
   */
  const register = (registerRequestDTO: RegisterRequestDTO) => {
    return customInstance<ResultBoolean>({
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequestDTO,
    });
  };
  /**
   * @summary 忘记密码-修改密码
   */
  const updatePassword = (updatePasswordRequestDTO: UpdatePasswordRequestDTO) => {
    return customInstance<ResultBoolean>({
      url: `/api/auth/password`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updatePasswordRequestDTO,
    });
  };
  /**
   * @summary 登录或注册
   */
  const loginOrRegister = (loginInParam: LoginInParam) => {
    return customInstance<ResultLoginVO>({
      url: `/api/auth/loginOrRegister`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginInParam,
    });
  };
  /**
   * @summary 验证码确认登录/注册
   */
  const confirmVerifyCode = (registerRequestDTO: RegisterRequestDTO) => {
    return customInstance<ResultUserLoginVO>({
      url: `/api/auth/confirm`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequestDTO,
    });
  };
  /**
   * @summary 发送验证码
   */
  const sendVerifyCode = (verifyCodeRequestDTO: VerifyCodeRequestDTO) => {
    return customInstance<ResultString>({
      url: `/api/auth/code`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: verifyCodeRequestDTO,
    });
  };
  /**
   * @summary 获取VAPID公钥
   */
  const getVapidPublicKey = () => {
    return customInstance<ResultString>({ url: `/api/auth/vapidPublicKey`, method: 'GET' });
  };
  return {
    register,
    updatePassword,
    loginOrRegister,
    confirmVerifyCode,
    sendVerifyCode,
    getVapidPublicKey,
  };
};
export type RegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['register']>>
>;
export type UpdatePasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['updatePassword']>>
>;
export type LoginOrRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['loginOrRegister']>>
>;
export type ConfirmVerifyCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['confirmVerifyCode']>>
>;
export type SendVerifyCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['sendVerifyCode']>>
>;
export type GetVapidPublicKeyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>['getVapidPublicKey']>>
>;
