/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  DetectNamingTypeParams,
  GetJavaBestPracticesParams,
  GetNameSuggestionParams,
  GetRawResponseParams,
  OptimizePromptParams,
  ResultJSONObject,
  ResultJavaBestPracticeResponseVO,
  ResultNamingTypeSuggestion,
  ResultPromptOptimizationResponseVO,
  ResultVariableNamingResponseVO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getAi = () => {
  /**
   * @summary DeepSeek计费
   */
  const queryBalance = () => {
    return customInstance<ResultJSONObject>({ url: `/api/ai/queryBalance`, method: 'GET' });
  };
  /**
   * @summary 优化AI提示词
   */
  const optimizePrompt = (params: OptimizePromptParams) => {
    return customInstance<ResultPromptOptimizationResponseVO>({
      url: `/api/ai/optimizePrompt`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 获取原生的响应
   */
  const getRawResponse = (params: GetRawResponseParams) => {
    return customInstance<ResultJSONObject>({
      url: `/api/ai/getRawResponse`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 获取Java开发最佳实践建议
   */
  const getJavaBestPractices = (params: GetJavaBestPracticesParams) => {
    return customInstance<ResultJavaBestPracticeResponseVO>({
      url: `/api/ai/getJavaBestPractices`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 获取命名建议
   */
  const getNameSuggestion = (params: GetNameSuggestionParams) => {
    return customInstance<ResultVariableNamingResponseVO>({
      url: `/api/ai/getAiNameSuggestion`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 检测命名类型
   */
  const detectNamingType = (params: DetectNamingTypeParams) => {
    return customInstance<ResultNamingTypeSuggestion>({
      url: `/api/ai/detectNamingType`,
      method: 'GET',
      params,
    });
  };
  return {
    queryBalance,
    optimizePrompt,
    getRawResponse,
    getJavaBestPractices,
    getNameSuggestion,
    detectNamingType,
  };
};
export type QueryBalanceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['queryBalance']>>
>;
export type OptimizePromptResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['optimizePrompt']>>
>;
export type GetRawResponseResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['getRawResponse']>>
>;
export type GetJavaBestPracticesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['getJavaBestPractices']>>
>;
export type GetNameSuggestionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['getNameSuggestion']>>
>;
export type DetectNamingTypeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['detectNamingType']>>
>;
