/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  DetectNamingTypeParams,
  GetAiNameSuggestionParams,
  GetJavaBestPracticesParams,
  OptimizePromptParams,
  ResultJavaBestPracticeResponseVO,
  ResultNamingTypeSuggestion,
  ResultPromptOptimizationResponseVO,
  ResultVariableNamingResponseVO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getAi = () => {
  /**
   * @summary 优化AI提示词
   */
  const optimizePrompt = (params: OptimizePromptParams) => {
    return customInstance<ResultPromptOptimizationResponseVO>({
      url: `/api/optimizePrompt`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 获取Java开发最佳实践建议
   */
  const getJavaBestPractices = (params: GetJavaBestPracticesParams) => {
    return customInstance<ResultJavaBestPracticeResponseVO>({
      url: `/api/getJavaBestPractices`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 获取AI命名建议
   */
  const getAiNameSuggestion = (params: GetAiNameSuggestionParams) => {
    return customInstance<ResultVariableNamingResponseVO>({
      url: `/api/getAiNameSuggestion`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 检测命名类型
   */
  const detectNamingType = (params: DetectNamingTypeParams) => {
    return customInstance<ResultNamingTypeSuggestion>({
      url: `/api/detectNamingType`,
      method: 'GET',
      params,
    });
  };
  return { optimizePrompt, getJavaBestPractices, getAiNameSuggestion, detectNamingType };
};
export type OptimizePromptResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['optimizePrompt']>>
>;
export type GetJavaBestPracticesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['getJavaBestPractices']>>
>;
export type GetAiNameSuggestionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['getAiNameSuggestion']>>
>;
export type DetectNamingTypeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAi>['detectNamingType']>>
>;
