/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdTravelGuideDTO } from '../api.schemas';

export const getGetTravelGuideResponseMock = (
  overrideResponse: Partial<CmdTravelGuideDTO> = {},
): CmdTravelGuideDTO => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      destination: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      introduction: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      attractions: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
          name: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          description: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          location: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          bestTime: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
        })),
        undefined,
      ]),
      tips: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetTravelGuideMockHandler = (
  overrideResponse?:
    | CmdTravelGuideDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdTravelGuideDTO> | CmdTravelGuideDTO),
) => {
  return http.get('*/api/travel-guide', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTravelGuideResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getTravelGuideMock = () => [getGetTravelGuideMockHandler()];
