/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { GetTravelGuideParams, ResultTravelGuideDTO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getTravelGuide = () => {
  /**
   * @summary 获取旅游攻略
   */
  const getTravelGuide = (params?: GetTravelGuideParams) => {
    return customInstance<ResultTravelGuideDTO>({
      url: `/api/travel-guide`,
      method: 'GET',
      params,
    });
  };
  return { getTravelGuide };
};
export type GetTravelGuideResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTravelGuide>['getTravelGuide']>>
>;
