/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  GetParseHistoryParams,
  ParseMessageFromImageBody,
  ParseMessageFromImageParams,
  ResultBoolean,
  ResultListMessageParseResultVO,
  ResultMessageParseResultVO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getMessageParse = () => {
  /**
   * @summary 删除解析结果
   */
  const deleteParseResult = (id: number) => {
    return customInstance<ResultBoolean>({
      url: `/api/message-parse/${id}/delete`,
      method: 'POST',
    });
  };
  /**
   * 上传图片，通过OCR识别后解析出人员、公司、产品信息
   * @summary 解析图片中的消息内容
   */
  const parseMessageFromImage = (
    parseMessageFromImageBody: ParseMessageFromImageBody,
    params?: ParseMessageFromImageParams,
  ) => {
    const formData = new FormData();
    formData.append('imageFile', parseMessageFromImageBody.imageFile);

    return customInstance<ResultMessageParseResultVO>({
      url: `/api/message-parse/parse-image`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      params,
    });
  };
  /**
   * @summary 获取解析历史记录
   */
  const getParseHistory = (params?: GetParseHistoryParams) => {
    return customInstance<ResultListMessageParseResultVO>({
      url: `/api/message-parse/history`,
      method: 'POST',
      params,
    });
  };
  /**
   * @summary 获取解析结果详情
   */
  const getParseResultById = (id: number) => {
    return customInstance<ResultMessageParseResultVO>({
      url: `/api/message-parse/detail/${id}`,
      method: 'POST',
    });
  };
  return { deleteParseResult, parseMessageFromImage, getParseHistory, getParseResultById };
};
export type DeleteParseResultResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessageParse>['deleteParseResult']>>
>;
export type ParseMessageFromImageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessageParse>['parseMessageFromImage']>>
>;
export type GetParseHistoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessageParse>['getParseHistory']>>
>;
export type GetParseResultByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessageParse>['getParseResultById']>>
>;
