/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  DevLog,
  QueryDevLogInParam,
  ResultBoolean,
  ResultIPageDevLogVO,
  ResultString,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDevLog = () => {
  /**
   * @summary 删除开发日志
   */
  const deleteDevLog = (id: string) => {
    return customInstance<ResultString>({ url: `/api/devLog/${id}/deleteDevLog`, method: 'POST' });
  };
  /**
   * @summary 更新开发日志
   */
  const updateDevLog = (devLog: DevLog) => {
    return customInstance<ResultBoolean>({
      url: `/api/devLog/updateDevLog`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: devLog,
    });
  };
  /**
   * @summary 新增开发日志
   */
  const saveDevLog = (devLog: DevLog) => {
    return customInstance<ResultBoolean>({
      url: `/api/devLog/saveDevLog`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: devLog,
    });
  };
  /**
   * @summary 分页查询开发日志
   */
  const queryDevLog = (queryDevLogInParam: QueryDevLogInParam) => {
    return customInstance<ResultIPageDevLogVO>({
      url: `/api/devLog/queryDevLog`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: queryDevLogInParam,
    });
  };
  return { deleteDevLog, updateDevLog, saveDevLog, queryDevLog };
};
export type DeleteDevLogResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevLog>['deleteDevLog']>>
>;
export type UpdateDevLogResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevLog>['updateDevLog']>>
>;
export type SaveDevLogResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevLog>['saveDevLog']>>
>;
export type QueryDevLogResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevLog>['queryDevLog']>>
>;
