/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultMapStringObject } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const get = () => {
  /**
   * @summary 测试代理连接
   */
  const testProxy = () => {
    return customInstance<ResultMapStringObject>({ url: `/proxy/test`, method: 'GET' });
  };
  /**
   * @summary 测试Gemini API连接
   */
  const testGeminiConnection = () => {
    return customInstance<ResultMapStringObject>({ url: `/proxy/test-gemini`, method: 'GET' });
  };
  /**
   * @summary 获取代理配置信息
   */
  const getProxyConfig = () => {
    return customInstance<ResultMapStringObject>({ url: `/proxy/config`, method: 'GET' });
  };
  return { testProxy, testGeminiConnection, getProxyConfig };
};
export type TestProxyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['testProxy']>>>;
export type TestGeminiConnectionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['testGeminiConnection']>>
>;
export type GetProxyConfigResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['getProxyConfig']>>
>;
