/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdBoolean } from '../api.schemas';

export const getTravelPlanCreateResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getTravelPlanDeleteResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getTravelPlanCreateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.post('*/api/travelPlan', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getTravelPlanCreateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getTravelPlanDeleteMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.delete('*/api/travelPlan/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getTravelPlanDeleteResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getTravelPlanMock = () => [
  getTravelPlanCreateMockHandler(),
  getTravelPlanDeleteMockHandler(),
];
