/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { CmdBoolean, TravelPlanEntity } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getTravelPlan = () => {
  /**
   * @summary 新增
   */
  const travelPlanCreate = (travelPlanEntity: TravelPlanEntity) => {
    return customInstance<CmdBoolean>({
      url: `/api/travelPlan`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: travelPlanEntity,
    });
  };
  /**
   * @summary 删除
   */
  const travelPlanDelete = (id: number) => {
    return customInstance<CmdBoolean>({ url: `/api/travelPlan/${id}`, method: 'DELETE' });
  };
  return { travelPlanCreate, travelPlanDelete };
};
export type TravelPlanCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTravelPlan>['travelPlanCreate']>>
>;
export type TravelPlanDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTravelPlan>['travelPlanDelete']>>
>;
