/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  GetAllTablesParams,
  GetTableInfoInParam,
  ResultListString,
  ResultTableInfoVO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDatabaseInfo = () => {
  /**
   * @summary 获取指定表的定义信息
   */
  const getTableInfo = (getTableInfoInParam: GetTableInfoInParam) => {
    return customInstance<ResultTableInfoVO>({
      url: `/api/database/tableInfo`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getTableInfoInParam,
    });
  };
  /**
   * @summary 获取所有表列表
   */
  const getAllTables = (params?: GetAllTablesParams) => {
    return customInstance<ResultListString>({ url: `/api/database/tables`, method: 'GET', params });
  };
  return { getTableInfo, getAllTables };
};
export type GetTableInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDatabaseInfo>['getTableInfo']>>
>;
export type GetAllTablesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDatabaseInfo>['getAllTables']>>
>;
