/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { GetTestTokenParams } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getToken = () => {
  const getTestToken = (params?: GetTestTokenParams) => {
    return customInstance<string>({ url: `/api/test/token`, method: 'GET', params });
  };
  return { getTestToken };
};
export type GetTestTokenResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getToken>['getTestToken']>>
>;
