/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { DecisionAnalysis, ResultBoolean } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getAnalysis = () => {
  /**
   * @summary 新增决策分析
   */
  const saveAnalysis = (decisionAnalysis: DecisionAnalysis) => {
    return customInstance<ResultBoolean>({
      url: `/api/saveAnalysis`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: decisionAnalysis,
    });
  };
  return { saveAnalysis };
};
export type SaveAnalysisResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnalysis>['saveAnalysis']>>
>;
