/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  DevLog,
  DevelopmentLogListParams,
  ResultBoolean,
  ResultDevLog,
  ResultIPageDevLogVO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDevelopmentLog = () => {
  /**
   * @summary 获取日志列表
   */
  const developmentLogList = (params: DevelopmentLogListParams) => {
    return customInstance<ResultIPageDevLogVO>({
      url: `/api/developmentLog`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary 更新
   */
  const developmentLogUpdate = (devLog: DevLog) => {
    return customInstance<ResultBoolean>({
      url: `/api/developmentLog`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: devLog,
    });
  };
  /**
   * @summary 新增
   */
  const developmentLogCreate = (devLog: DevLog) => {
    return customInstance<ResultBoolean>({
      url: `/api/developmentLog`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: devLog,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const developmentLogGetById = (id: number) => {
    return customInstance<ResultDevLog>({ url: `/api/developmentLog/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除
   */
  const developmentLogDelete = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/developmentLog/${id}`, method: 'DELETE' });
  };
  return {
    developmentLogList,
    developmentLogUpdate,
    developmentLogCreate,
    developmentLogGetById,
    developmentLogDelete,
  };
};
export type DevelopmentLogListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevelopmentLog>['developmentLogList']>>
>;
export type DevelopmentLogUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevelopmentLog>['developmentLogUpdate']>>
>;
export type DevelopmentLogCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevelopmentLog>['developmentLogCreate']>>
>;
export type DevelopmentLogGetByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevelopmentLog>['developmentLogGetById']>>
>;
export type DevelopmentLogDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevelopmentLog>['developmentLogDelete']>>
>;
