/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdBoolean, CmdCustomPageObject, CmdDevelopmentLogEntity } from '../api.schemas';

export const getDevelopmentLogListResponseMock = (
  overrideResponse: Partial<CmdCustomPageObject> = {},
): CmdCustomPageObject => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      records: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
          () => ({}),
        ),
        undefined,
      ]),
      total: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      size: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      current: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      orders: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
          column: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          asc: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
        })),
        undefined,
      ]),
      optimizeCountSql: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      searchCount: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      optimizeJoinOfCountSql: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      maxLimit: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      countId: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      pages: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getDevelopmentLogUpdateResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDevelopmentLogCreateResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDevelopmentLogGetByIdResponseMock = (
  overrideResponse: Partial<CmdDevelopmentLogEntity> = {},
): CmdDevelopmentLogEntity => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      content: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      progress: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getDevelopmentLogDeleteResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getDevelopmentLogListMockHandler = (
  overrideResponse?:
    | CmdCustomPageObject
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdCustomPageObject> | CmdCustomPageObject),
) => {
  return http.get('*/api/developmentLog', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDevelopmentLogListResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDevelopmentLogUpdateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.put('*/api/developmentLog', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDevelopmentLogUpdateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDevelopmentLogCreateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.post('*/api/developmentLog', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDevelopmentLogCreateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDevelopmentLogGetByIdMockHandler = (
  overrideResponse?:
    | CmdDevelopmentLogEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdDevelopmentLogEntity> | CmdDevelopmentLogEntity),
) => {
  return http.get('*/api/developmentLog/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDevelopmentLogGetByIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDevelopmentLogDeleteMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.delete('*/api/developmentLog/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDevelopmentLogDeleteResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getDevelopmentLogMock = () => [
  getDevelopmentLogListMockHandler(),
  getDevelopmentLogUpdateMockHandler(),
  getDevelopmentLogCreateMockHandler(),
  getDevelopmentLogGetByIdMockHandler(),
  getDevelopmentLogDeleteMockHandler(),
];
