/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultBoolean, ResultGetAllUserVO, ResultListGetAllUserVO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getUser = () => {
  /**
   * @summary 退出登录
   */
  const logout = () => {
    return customInstance<ResultBoolean>({ url: `/api/user/logout`, method: 'POST' });
  };
  /**
   * @summary 查询用户
   */
  const queryUser = () => {
    return customInstance<ResultListGetAllUserVO>({ url: `/api/user/queryUser`, method: 'GET' });
  };
  /**
   * @summary 获取当前用户信息
   */
  const getCurrentUser = () => {
    return customInstance<ResultGetAllUserVO>({ url: `/api/user/me`, method: 'GET' });
  };
  return { logout, queryUser, getCurrentUser };
};
export type LogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['logout']>>>;
export type QueryUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUser>['queryUser']>>
>;
export type GetCurrentUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUser>['getCurrentUser']>>
>;
