/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { ResultBoolean, ResultUserResponseDTO } from '../api.schemas';

export const getUserLogoutResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getUserMeResponseMock = (
  overrideResponse: Partial<ResultUserResponseDTO> = {},
): ResultUserResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      username: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      email: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      role: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      avatarUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getUserLogoutMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.post('*/api/user/logout', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUserLogoutResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getUserMeMockHandler = (
  overrideResponse?:
    | ResultUserResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultUserResponseDTO> | ResultUserResponseDTO),
) => {
  return http.get('*/api/user/me', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUserMeResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getUserMock = () => [getUserLogoutMockHandler(), getUserMeMockHandler()];
