/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdString, CmdUserResponseDTO } from '../api.schemas';

export const getUserPasswordResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getUserLogoutResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getUserMeResponseMock = (
  overrideResponse: Partial<CmdUserResponseDTO> = {},
): CmdUserResponseDTO => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      username: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      email: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      needResetPassword: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      role: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      avatarUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getUserPasswordMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.put('*/api/user/password', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUserPasswordResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getUserLogoutMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.post('*/api/user/logout', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUserLogoutResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getUserMeMockHandler = (
  overrideResponse?:
    | CmdUserResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdUserResponseDTO> | CmdUserResponseDTO),
) => {
  return http.get('*/api/user/me', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUserMeResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getUserMock = () => [
  getUserPasswordMockHandler(),
  getUserLogoutMockHandler(),
  getUserMeMockHandler(),
];
