/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultBoolean, ResultUserResponseDTO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getUser = () => {
  /**
   * @summary 退出登录
   */
  const userLogout = () => {
    return customInstance<ResultBoolean>({ url: `/api/user/logout`, method: 'POST' });
  };
  /**
   * @summary 获取当前用户信息
   */
  const userMe = () => {
    return customInstance<ResultUserResponseDTO>({ url: `/api/user/me`, method: 'GET' });
  };
  return { userLogout, userMe };
};
export type UserLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUser>['userLogout']>>
>;
export type UserMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUser>['userMe']>>>;
