/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { customInstance } from '../../boot/orval-client';

export const getEmail = () => {
  /**
   * @summary 微博签到提醒
   */
  const sendWeiboSignEmail = () => {
    return customInstance<void>({ url: `/api/email/sendWeiboSignEmail`, method: 'GET' });
  };
  /**
   * @summary 待办提醒
   */
  const sendTodoEmail = () => {
    return customInstance<void>({ url: `/api/email/sendTodoEmail`, method: 'GET' });
  };
  /**
   * @summary 今日提醒
   */
  const sendTodayEmail = () => {
    return customInstance<void>({ url: `/api/email/sendTodayEmail`, method: 'GET' });
  };
  /**
   * @summary 红包使用提醒
   */
  const sendRedPackageEmail = () => {
    return customInstance<void>({ url: `/api/email/sendRedPackageEmail`, method: 'GET' });
  };
  return { sendWeiboSignEmail, sendTodoEmail, sendTodayEmail, sendRedPackageEmail };
};
export type SendWeiboSignEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEmail>['sendWeiboSignEmail']>>
>;
export type SendTodoEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEmail>['sendTodoEmail']>>
>;
export type SendTodayEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEmail>['sendTodayEmail']>>
>;
export type SendRedPackageEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEmail>['sendRedPackageEmail']>>
>;
