/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultString, SendTemplateEmailInParam } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getEmail = () => {
  /**
   * @summary 通用模板邮件发送
   */
  const sendTemplateEmail = (sendTemplateEmailInParam: SendTemplateEmailInParam) => {
    return customInstance<ResultString>({
      url: `/api/email/send-template`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sendTemplateEmailInParam,
    });
  };
  /**
   * @summary 待办
   */
  const sendTodoEmail = () => {
    return customInstance<void>({ url: `/api/email/sendTodoEmail`, method: 'GET' });
  };
  /**
   * @summary 提醒我
   */
  const remindMe = () => {
    return customInstance<ResultString>({ url: `/api/email/remindMe`, method: 'GET' });
  };
  return { sendTemplateEmail, sendTodoEmail, remindMe };
};
export type SendTemplateEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEmail>['sendTemplateEmail']>>
>;
export type SendTodoEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEmail>['sendTodoEmail']>>
>;
export type RemindMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEmail>['remindMe']>>
>;
