/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  CmdBoolean,
  CmdObject,
  CmdUserSettingsEntity,
  UpdateShowTicketsBody,
  UpdateShowTicketsParams,
  UserSettingsEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getUserSettings = () => {
  /**
   * @summary 更新用户设置
   */
  const update = (userSettingsEntity: UserSettingsEntity) => {
    return customInstance<CmdBoolean>({
      url: `/api/user/settings`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: userSettingsEntity,
    });
  };
  /**
   * @summary 保存用户设置
   */
  const save = (userSettingsEntity: UserSettingsEntity) => {
    return customInstance<CmdBoolean>({
      url: `/api/user/settings`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userSettingsEntity,
    });
  };
  /**
   * @summary 更新显示火车票设置
   */
  const updateShowTickets = (
    updateShowTicketsBody: UpdateShowTicketsBody,
    params: UpdateShowTicketsParams,
  ) => {
    return customInstance<CmdObject>({
      url: `/api/user/settings/show-tickets`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateShowTicketsBody,
      params,
    });
  };
  /**
   * @summary 根据ID获取用户设置
   */
  const getById = (id: number) => {
    return customInstance<CmdUserSettingsEntity>({
      url: `/api/user/settings/${id}`,
      method: 'GET',
    });
  };
  /**
   * @summary 删除用户设置
   */
  const _delete = (id: number) => {
    return customInstance<CmdBoolean>({ url: `/api/user/settings/${id}`, method: 'DELETE' });
  };
  return { update, save, updateShowTickets, getById, _delete };
};
export type UpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserSettings>['update']>>
>;
export type SaveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserSettings>['save']>>
>;
export type UpdateShowTicketsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserSettings>['updateShowTickets']>>
>;
export type GetByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserSettings>['getById']>>
>;
export type _DeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserSettings>['_delete']>>
>;
