/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdBoolean, CmdObject, CmdUserSettingsEntity } from '../api.schemas';

export const getUpdateResponseMock = (overrideResponse: Partial<CmdBoolean> = {}): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getSaveResponseMock = (overrideResponse: Partial<CmdBoolean> = {}): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getUpdateShowTicketsResponseMock = (
  overrideResponse: Partial<CmdObject> = {},
): CmdObject => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getGetByIdResponseMock = (
  overrideResponse: Partial<CmdUserSettingsEntity> = {},
): CmdUserSettingsEntity => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      userId: faker.number.int({ min: undefined, max: undefined }),
      settingKey: faker.string.alpha(20),
      settingValue: faker.string.alpha(20),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getDeleteResponseMock = (overrideResponse: Partial<CmdBoolean> = {}): CmdBoolean => ({
  code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getUpdateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.put('*/api/user/settings', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUpdateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSaveMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.post('*/api/user/settings', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSaveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getUpdateShowTicketsMockHandler = (
  overrideResponse?:
    | CmdObject
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdObject> | CmdObject),
) => {
  return http.post('*/api/user/settings/show-tickets', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUpdateShowTicketsResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetByIdMockHandler = (
  overrideResponse?:
    | CmdUserSettingsEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdUserSettingsEntity> | CmdUserSettingsEntity),
) => {
  return http.get('*/api/user/settings/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetByIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDeleteMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.delete('*/api/user/settings/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDeleteResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getUserSettingsMock = () => [
  getUpdateMockHandler(),
  getSaveMockHandler(),
  getUpdateShowTicketsMockHandler(),
  getGetByIdMockHandler(),
  getDeleteMockHandler(),
];
