/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  GeneralAccurateOcrBody,
  GeneralBasicOcrBody,
  GeneralHandwritingOcrBody,
  OcrByUrlParams,
  ResultOcrResultVO,
  TableOcrBody,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getOcr = () => {
  /**
   * @summary 表格识别
   */
  const tableOcr = (tableOcrBody: TableOcrBody) => {
    const formData = new FormData();
    formData.append('imageFile', tableOcrBody.imageFile);

    return customInstance<ResultOcrResultVO>({
      url: `/api/ocr/table`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };
  /**
   * @summary 通用手写体识别
   */
  const generalHandwritingOcr = (generalHandwritingOcrBody: GeneralHandwritingOcrBody) => {
    const formData = new FormData();
    formData.append('imageFile', generalHandwritingOcrBody.imageFile);

    return customInstance<ResultOcrResultVO>({
      url: `/api/ocr/handwriting`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };
  /**
   * @summary 通用印刷体识别
   */
  const generalBasicOcr = (generalBasicOcrBody: GeneralBasicOcrBody) => {
    const formData = new FormData();
    formData.append('imageFile', generalBasicOcrBody.imageFile);

    return customInstance<ResultOcrResultVO>({
      url: `/api/ocr/general-basic`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };
  /**
   * @summary 通用印刷体识别（高精度版）
   */
  const generalAccurateOcr = (generalAccurateOcrBody: GeneralAccurateOcrBody) => {
    const formData = new FormData();
    formData.append('imageFile', generalAccurateOcrBody.imageFile);

    return customInstance<ResultOcrResultVO>({
      url: `/api/ocr/general-accurate`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };
  /**
   * @summary 通过图片URL进行OCR识别
   */
  const ocrByUrl = (params: OcrByUrlParams) => {
    return customInstance<ResultOcrResultVO>({ url: `/api/ocr/by-url`, method: 'POST', params });
  };
  return { tableOcr, generalHandwritingOcr, generalBasicOcr, generalAccurateOcr, ocrByUrl };
};
export type TableOcrResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOcr>['tableOcr']>>
>;
export type GeneralHandwritingOcrResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOcr>['generalHandwritingOcr']>>
>;
export type GeneralBasicOcrResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOcr>['generalBasicOcr']>>
>;
export type GeneralAccurateOcrResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOcr>['generalAccurateOcr']>>
>;
export type OcrByUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOcr>['ocrByUrl']>>
>;
