/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
/**
 * API 统一返回格式
 */
export interface ResultString {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: string;
}

/**
 * 工作日志
 */
export interface WorkLogEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 日志内容 */
  content?: string;
  /** 日志日期 */
  logDate?: string;
  /** 用户ID */
  userId?: number;
}

/**
 * API 统一返回格式
 */
export interface ResultBoolean {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: boolean;
}

/**
 * 用户设置信息
 */
export interface UserSettingsEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 用户ID */
  userId: number;
  /** 设置键 */
  settingKey: string;
  /** 设置值 */
  settingValue: string;
}

/**
 * 平台跳转URL
 */
export interface UrlEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** URL所属分组 */
  tag?: string;
  /** URL名称 */
  name?: string;
  /** URL地址 */
  address?: string;
  /** 用户ID */
  userId?: number;
}

/**
 * 待办事项
 */
export interface TodoEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 待办事项名称 */
  title?: string;
  /** 待办事项描述 */
  description?: string;
  /** 是否完成 */
  completed?: boolean;
  /** 计划完成日期 */
  dueDate?: string;
  /** 优先级 */
  priority?: number;
  /** 类别/标签 */
  category?: string;
  /** 用户ID */
  userId?: number;
}

/**
 * 系统配置信息
 */
export interface SystemConfigEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 配置键 */
  configKey?: string;
  /** 配置值 */
  configValue?: string;
  /** 配置描述 */
  description?: string;
  /** 配置分组 */
  groupName?: string;
  /** 是否启用 */
  enabled?: boolean;
}

/**
 * 需求
 */
export interface RequirementEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 需求号 */
  requirementId?: string;
  /** 需求名称 */
  requirementName?: string;
  /** 需求关联的需求文档名称。如果关联多个需求文档，会以;进行分隔 */
  relatedRequirementDocs?: string;
  /** 需求关联的设计文档名称。如果关联多个设计文档，会以;进行分隔 */
  relatedDesignDocs?: string;
  /** 需求所属的系统分类 */
  systemCategory?: string;
  /** 需求的归属用户ID */
  userId?: number;
}

/**
 * 开发日志信息
 */
export interface DevelopmentLogEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 日志内容 */
  content?: string;
  /** 进度 */
  progress?: number;
}

/**
 * 每日任务信息
 */
export interface DailyTaskEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 任务标题 */
  title?: string;
  /** 任务内容 */
  content?: string;
  /** 所属用户ID */
  userId?: number;
  /** 任务状态：0-未开始，1-进行中，2-已完成，3-已取消 */
  status?: number;
  /** 任务优先级：0-低，1-中，2-高 */
  priority?: number;
  /** 计划开始时间 */
  plannedStartTime?: string;
  /** 计划结束时间 */
  plannedEndTime?: string;
  /** 实际完成时间 */
  completedTime?: string;
  /** 任务备注 */
  remarks?: string;
}

export interface UpdatePasswordRequestDTO {
  email?: string;
  /**
   * @minLength 6
   * @maxLength 6
   */
  code?: string;
  /**
   * @minLength 6
   * @maxLength 20
   */
  newPwd: string;
}

/**
 * 数据或错误信息
 */
export type ResultObjectPayload = { [key: string]: unknown };

/**
 * API 统一返回格式
 */
export interface ResultObject {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: ResultObjectPayload;
}

/**
 * 旅行计划信息
 */
export interface TravelPlanEntity {
  /** 主键ID */
  id?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 计划标题 */
  title?: string;
  /** 计划状态：0-待定，2-进行中，3-已完成 */
  status?: number;
  /** 出发时间 */
  departureTime?: string;
  /** 行程天数 */
  duration?: number;
  /** 行程里程(公里) */
  distance?: number;
  /** 预计花费 */
  estimatedCost?: number;
  /** 参与人数 */
  memberCount?: number;
  /** 备注信息 */
  remarks?: string;
}

/**
 * 扫码识别请求
 */
export interface ScanIdentifyRequestDTO {
  /** 二维码内容 */
  content: string;
}

/**
 * API 统一返回格式
 */
export interface ResultScanIdentifyResponseDTO {
  /** 是否成功 */
  success?: boolean;
  payload?: ScanIdentifyResponseDTO;
}

/**
 * 扫码识别响应
 */
export interface ScanIdentifyResponseDTO {
  /** 二维码类型:WECHAT/ALIPAY/UNKNOWN */
  type?: string;
  /** 处理后的URL */
  url?: string;
  /** 原始URL */
  fallbackUrl?: string;
}

/**
 * 加密密钥信息
 */
export interface Keys {
  /** P256DH密钥 */
  p256dh: string;
  /** 认证密钥 */
  auth: string;
}

/**
 * 推送订阅信息
 */
export interface SubscriptionRequestDTO {
  /** 终端点URL */
  endpoint: string;
  keys: Keys;
  /** 推送消息内容 */
  payload?: string;
  /** 过期时间 */
  expirationTime?: number;
}

export interface RegisterRequestDTO {
  email?: string;
  code?: string;
  password?: string;
}

export interface UserLoginRequestDTO {
  email: string;
  password: string;
}

/**
 * API 统一返回格式
 */
export interface ResultUserLoginResponseDTO {
  /** 是否成功 */
  success?: boolean;
  payload?: UserLoginResponseDTO;
}

/**
 * 用户登录响应
 */
export interface UserLoginResponseDTO {
  /** 用户token */
  token?: string;
  user?: UserResponseDTO;
}

/**
 * 用户信息
 */
export interface UserResponseDTO {
  id?: number;
  username?: string;
  email?: string;
  role?: string;
  avatarUrl?: string;
}

export interface VerifyCodeRequestDTO {
  type: string;
  email: string;
}

/**
 * API 统一返回格式
 */
export interface ResultWorkLogEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: WorkLogEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultListWorkLogEntity {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: WorkLogEntity[];
}

/**
 * 实时天气详细信息
 */
export interface Now {
  /** 数据观测时间 */
  obsTime?: string;
  /** 温度，单位：摄氏度 */
  temp?: string;
  /** 体感温度，单位：摄氏度 */
  feelsLike?: string;
  /** 天气图标代码 */
  icon?: string;
  /** 天气状况描述 */
  text?: string;
  /** 风向360角度 */
  wind360?: string;
  /** 风向 */
  windDir?: string;
  /** 风力等级 */
  windScale?: string;
  /** 风速，单位：公里/小时 */
  windSpeed?: string;
  /** 相对湿度，百分比 */
  humidity?: string;
  /** 当前小时累计降水量，单位：毫米 */
  precip?: string;
  /** 大气压强，单位：百帕 */
  pressure?: string;
  /** 能见度，单位：公里 */
  vis?: string;
  /** 云量，百分比 */
  cloud?: string;
  /** 露点温度 */
  dew?: string;
}

/**
 * 数据引用信息
 */
export interface Refer {
  /** 数据源 */
  sources?: string[];
  /** 许可证 */
  license?: string[];
}

/**
 * API 统一返回格式
 */
export interface ResultWeatherResponseDTO {
  /** 是否成功 */
  success?: boolean;
  payload?: WeatherResponseDTO;
}

/**
 * 天气信息响应
 */
export interface WeatherResponseDTO {
  /** API状态码 */
  code?: string;
  /** 最近更新时间 */
  updateTime?: string;
  /** 天气数据源链接 */
  fxLink?: string;
  now?: Now;
  refer?: Refer;
}

/**
 * API 统一返回格式
 */
export interface ResultUserSettingsEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: UserSettingsEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultUserResponseDTO {
  /** 是否成功 */
  success?: boolean;
  payload?: UserResponseDTO;
}

/**
 * API 统一返回格式
 */
export interface ResultUrlEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: UrlEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultListUrlEntity {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: UrlEntity[];
}

/**
 * 景点信息
 */
export interface Attraction {
  /** 景点名称 */
  name?: string;
  /** 景点描述 */
  description?: string;
  /** 景点位置 */
  location?: string;
  /** 最佳游览时间 */
  bestTime?: string;
}

/**
 * API 统一返回格式
 */
export interface ResultTravelGuideDTO {
  /** 是否成功 */
  success?: boolean;
  payload?: TravelGuideDTO;
}

/**
 * 旅游攻略响应
 */
export interface TravelGuideDTO {
  /** 目的地名称 */
  destination?: string;
  /** 目的地简介 */
  introduction?: string;
  /** 景点列表 */
  attractions?: Attraction[];
  /** 旅游建议 */
  tips?: string;
}

/**
 * API 统一返回格式
 */
export interface ResultTodoEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: TodoEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultListTodoEntity {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: TodoEntity[];
}

/**
 * API 统一返回格式
 */
export interface ResultSystemConfigEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: SystemConfigEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultListSystemConfigEntity {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: SystemConfigEntity[];
}

/**
 * API 统一返回格式
 */
export interface ResultRequirementEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: RequirementEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultListString {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: string[];
}

/**
 * API 统一返回格式
 */
export interface ResultListRequirementEntity {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: RequirementEntity[];
}

export type CustomPageObjectRecordsItem = { [key: string]: unknown };

/**
 * 自定义分页对象
 */
export interface CustomPageObject {
  records?: CustomPageObjectRecordsItem[];
  total?: number;
  size?: number;
  current?: number;
  /** @deprecated */
  orders?: OrderItem[];
  /** @deprecated */
  optimizeCountSql?: boolean;
  /** @deprecated */
  searchCount?: boolean;
  optimizeJoinOfCountSql?: boolean;
  /** @deprecated */
  maxLimit?: number;
  /** @deprecated */
  countId?: string;
  pages?: number;
}

export interface OrderItem {
  column?: string;
  asc?: boolean;
}

/**
 * API 统一返回格式
 */
export interface ResultCustomPageObject {
  /** 是否成功 */
  success?: boolean;
  payload?: CustomPageObject;
}

/**
 * API 统一返回格式
 */
export interface ResultDevelopmentLogEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: DevelopmentLogEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultDailyTaskEntity {
  /** 是否成功 */
  success?: boolean;
  payload?: DailyTaskEntity;
}

/**
 * API 统一返回格式
 */
export interface ResultListDailyTaskEntity {
  /** 是否成功 */
  success?: boolean;
  /** 数据或错误信息 */
  payload?: DailyTaskEntity[];
}

export type DevelopmentLogListParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  size?: number;
};

export type UpdateShowTicketsParams = {
  /**
   * 用户ID
   */
  userId: number;
};

export type UpdateShowTicketsBody = { [key: string]: boolean };

export type TestUploadBody = {
  file: Blob;
};

export type GetTravelGuideParams = {
  /**
   * 目的地名称
   */
  destination?: string;
};

export type GetTestTokenParams = {
  hours?: number;
};

export type DeepseekTestParams = {
  /**
   * 提示词
   */
  prompt?: string;
};

export type GetSignedUrlParams = {
  objectName: string;
};

export type GetPublicUrlParams = {
  objectName: string;
};

export type TestDeleteParams = {
  objectName: string;
};
