/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
export interface ResultString {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: string;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 工作日志
 */
export interface WorkLogEntity {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 日志内容 */
  content?: string;
  /** 日志日期 */
  logDate?: string;
  /** 用户ID */
  userId?: number;
}

export interface ResultBoolean {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: boolean;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 用户设置信息
 */
export interface UserSettingsEntity {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 用户ID */
  userId: number;
  /** 设置键 */
  settingKey: string;
  /** 设置值 */
  settingValue: string;
}

/**
 * 系统配置信息
 */
export interface SysConfig {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 配置键 */
  configKey?: string;
  /** 配置值 */
  configValue?: string;
  /** 配置描述 */
  description?: string;
  /** 配置分组 */
  groupName?: string;
  /** 是否启用 */
  enabled?: boolean;
}

/**
 * 每日任务信息
 */
export interface DailyTask {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 任务标题 */
  title?: string;
  /** 任务内容 */
  content?: string;
  /** 所属用户ID */
  userId?: number;
  /** 任务状态：0-未开始，1-进行中，2-已完成，3-已取消 */
  status?: number;
  /** 任务优先级：0-低，1-中，2-高 */
  priority?: number;
  /** 计划开始时间 */
  plannedStartTime?: string;
  /** 计划结束时间 */
  plannedEndTime?: string;
  /** 实际完成时间 */
  completedTime?: string;
  /** 任务备注 */
  remarks?: string;
}

/**
 * 成功数据
 */
export type ResultObjectOkData = { [key: string]: unknown };

export interface ResultObject {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: ResultObjectOkData;
  /** 失败消息 */
  failMsg?: string;
}

export interface UpdateUrlInParam {
  /** 主键ID */
  id?: string;
  /** URL所属分组 */
  tag?: string;
  /** URL名称 */
  name?: string;
  /** URL地址 */
  address?: string;
  /** 是否置顶 */
  isTop?: number;
}

export interface ResultSysUrl {
  /** 是否成功 */
  isOk?: boolean;
  okData?: SysUrl;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 成功数据
 */
export interface SysUrl {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** URL所属分组 */
  tag?: string;
  /** URL名称 */
  name?: string;
  /** URL地址 */
  address?: string;
  /** 用户ID */
  userId?: number;
  /** 是否置顶 */
  isTop?: number;
}

export interface UpdateUrlCategoryInParam {
  /** 旧分类名称 */
  oldTag: string;
  /** 新分类名称 */
  newTag: string;
}

export interface SaveUrlInParam {
  /** URL所属分组 */
  tag?: string;
  /** URL名称 */
  name?: string;
  /** URL地址 */
  address?: string;
  /** 是否置顶 */
  isTop?: number;
}

export interface GetUrlByConditionInParam {
  /** URL所属分组 */
  tag?: string;
  /** URL名称 */
  name?: string;
  /** URL地址 */
  address?: string;
  /** 用户ID */
  userId?: string;
}

export interface ResultListSysUrl {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: SysUrl[];
  /** 失败消息 */
  failMsg?: string;
}

export interface GetTodoByConditionInParam {
  /** 主键ID */
  id?: string;
  /** 类别/标签 */
  category?: string;
  /** 用户ID */
  userId?: string;
}

export interface ResultListTodoVO {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: TodoVO[];
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 成功数据
 */
export interface TodoVO {
  /** 主键ID */
  id?: string;
  /** 待办事项名称 */
  title?: string;
  /** 待办事项描述 */
  description?: string;
  /** 是否完成 */
  completed?: boolean;
  /** 优先级 */
  priority?: number;
  /** 类别/标签 */
  category?: string;
  /** 用户ID */
  userId?: number;
}

/**
 * 旅行计划信息
 */
export interface TravelPlanEntity {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 计划标题 */
  title?: string;
  /** 计划状态：0-待定，2-进行中，3-已完成 */
  status?: number;
  /** 出发时间 */
  departureTime?: string;
  /** 行程天数 */
  duration?: number;
  /** 行程里程(公里) */
  distance?: number;
  /** 预计花费 */
  estimatedCost?: number;
  /** 参与人数 */
  memberCount?: number;
  /** 备注信息 */
  remarks?: string;
}

/**
 * 待办事项
 */
export interface Todo {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 待办事项名称 */
  title?: string;
  /** 待办事项描述 */
  description?: string;
  /** 是否完成 */
  completed?: boolean;
  /** 优先级 */
  priority?: number;
  /** 类别/标签 */
  category?: string;
  /** 用户ID */
  userId?: number;
}

export interface ResultTodo {
  /** 是否成功 */
  isOk?: boolean;
  okData?: Todo;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultSaveSysFileVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: SaveSysFileVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 成功数据
 */
export interface SaveSysFileVO {
  /** 主键ID */
  id?: string;
  /** 文件类型 */
  fileType?: string;
  /** 文件名称 */
  fileName?: string;
  /** 文件地址 */
  fileUrl?: string;
  /** 开发任务ID */
  devTaskId?: string;
}

/**
 * 扫码识别请求
 */
export interface ScanIdentifyRequestDTO {
  /** 二维码内容 */
  content: string;
}

export interface ResultScanIdentifyResponseVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: ScanIdentifyResponseVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 扫码识别响应
 */
export interface ScanIdentifyResponseVO {
  /** 二维码类型:WECHAT/ALIPAY/UNKNOWN */
  type?: string;
  /** 处理后的URL */
  url?: string;
  /** 原始URL */
  fallbackUrl?: string;
}

/**
 * 决策分析表
 */
export interface DecisionAnalysis {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 分析的话题 */
  analysisTopic?: string;
  /** 分析的角度 */
  analysisPerspective?: string;
  /** 分析的结论 */
  analysisConclusion?: string;
}

/**
 * 加密密钥信息
 */
export interface Keys {
  /** P256DH密钥 */
  p256dh: string;
  /** 认证密钥 */
  auth: string;
}

/**
 * 推送订阅信息
 */
export interface SubscriptionRequestDTO {
  /** 终端点URL */
  endpoint: string;
  keys: Keys;
  /** 推送消息内容 */
  payload?: string;
  /** 过期时间 */
  expirationTime?: number;
}

export interface UpdateDevTaskInParam {
  /** 任务id */
  id?: string;
  /** 是否置顶 */
  isTop?: number;
}

/**
 * 需求
 */
export interface DevTask {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 需求编号 */
  requirementId?: string;
  /** 需求名称 */
  requirementName?: string;
  /** 需求关联的需求文档名称。如果关联多个需求文档，会以;进行分隔 */
  relatedRequirementDocs?: string;
  /** 系统分类 */
  systemCategory?: string;
  /** 需求的归属用户ID */
  userId?: number;
}

export interface ResultDevTask {
  /** 是否成功 */
  isOk?: boolean;
  okData?: DevTask;
  /** 失败消息 */
  failMsg?: string;
}

export interface SaveDevTaskInParam {
  /** 需求编号 */
  requirementId?: string;
  /** 需求名称 */
  requirementName?: string;
  /** 需求关联的需求文档名称。如果关联多个需求文档，会以;进行分隔 */
  relatedRequirementDocs?: string;
  /** 系统分类 */
  systemCategory?: string;
  /** 上传的文件列表 */
  uploadedFilesId?: string[];
  /** 需求的归属用户ID */
  userId?: number;
}

/**
 * 分页参数
 */
export interface PageParam {
  /** 当前页 */
  current?: number;
  /** 每页显示条数，默认 10 */
  size?: number;
}

export interface QueryDevTaskInParam {
  /** 主键ID */
  id?: string;
  /** 需求编号 */
  requirementId?: string;
  /** 需求名称 */
  requirementName?: string;
  /** 需求关联的需求文档名称。如果关联多个需求文档，会以;进行分隔 */
  relatedRequirementDocs?: string;
  /** 需求关联的设计文档名称。如果关联多个设计文档，会以;进行分隔 */
  relatedDesignDocs?: string;
  /** 系统分类 */
  systemCategory?: string;
  /** 需求的归属用户ID */
  userId?: number;
  pageParam?: PageParam;
}

export interface DevTaskVO {
  /** 主键ID */
  id?: string;
  /** 需求编号 */
  requirementId?: string;
  /** 需求名称 */
  requirementName?: string;
  /** 需求关联的文件 */
  relatedFileList?: RelatedFile[];
  /** 系统分类 */
  systemCategory?: string;
  systemCategoryDesc?: string;
  /** 需求的归属用户ID */
  userId?: number;
  /** 关联的文件 */
  sysFileId?: string;
}

/**
 * 成功数据
 */
export interface IPageDevTaskVO {
  size?: number;
  pages?: number;
  total?: number;
  current?: number;
  records?: DevTaskVO[];
}

/**
 * 需求关联的文件
 */
export interface RelatedFile {
  /** 文件类型 */
  fileType?: string;
  /** 文件名称 */
  fileName?: string;
  /** 文件地址 */
  fileUrl?: string;
  /** 文件数量 */
  fileCount?: number;
  /** 创建时间 */
  createdAt?: string;
}

export interface ResultIPageDevTaskVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: IPageDevTaskVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 开发日志信息
 */
export interface DevLog {
  /** 主键ID */
  id?: number;
  /** 是否有效 */
  isValid?: number;
  /** 创建人 */
  createdBy?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新人 */
  updatedBy?: number;
  /** 更新时间 */
  updatedAt?: string;
  /** 日志内容 */
  content?: string;
  /** 进度 */
  progress?: number;
}

export interface QueryDevLogInParam {
  /** 主键ID */
  id?: string;
  pageParam?: PageParam;
}

/**
 * 开发日志响应
 */
export interface DevLogVO {
  /** 日志ID */
  id?: number;
  /** 日志内容 */
  content?: string;
  /** 进度 */
  progress?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新时间 */
  updatedAt?: string;
}

/**
 * 成功数据
 */
export interface IPageDevLogVO {
  size?: number;
  pages?: number;
  total?: number;
  current?: number;
  records?: DevLogVO[];
}

export interface ResultIPageDevLogVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: IPageDevLogVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 获取表定义信息请求参数
 */
export interface GetTableInfoInParam {
  /** 表名 */
  tableName: string;
  /** 模式名（可选） */
  schemaName?: string;
}

export interface ResultTableInfoVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: TableInfoVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 表字段信息
 */
export interface TableColumnInfoVO {
  /** 字段名 */
  columnName?: string;
  /** 数据类型 */
  dataType?: string;
  /** 是否允许为空 */
  isNullable?: string;
  /** 默认值 */
  columnDefault?: string;
  /** 字段注释 */
  columnComment?: string;
  /** 字符最大长度 */
  characterMaximumLength?: number;
  /** 数字精度 */
  numericPrecision?: number;
  /** 数字小数位数 */
  numericScale?: number;
  /** 字段序号 */
  ordinalPosition?: number;
}

/**
 * 表定义信息
 */
export interface TableInfoVO {
  /** 表名 */
  tableName?: string;
  /** 模式名 */
  schemaName?: string;
  /** 表注释 */
  tableComment?: string;
  /** 表类型 */
  tableType?: string;
  /** 字段信息列表 */
  columns?: TableColumnInfoVO[];
}

export interface RegisterRequestDTO {
  email?: string;
  code?: string;
  password?: string;
}

export interface UpdatePasswordRequestDTO {
  email?: string;
  /**
   * @minLength 6
   * @maxLength 6
   */
  code?: string;
  /**
   * @minLength 6
   * @maxLength 20
   */
  newPwd: string;
}

export interface LoginInParam {
  /** 邮箱 */
  email?: string;
}

/**
 * 用户信息
 */
export interface GetAllUserVO {
  id?: number;
  username?: string;
  email?: string;
  role?: string;
  avatarUrl?: string;
}

/**
 * 登录响应
 */
export interface LoginVO {
  /** 状态类型：SEND_CODE - 已发送验证码，LOGIN_SUCCESS - 登录成功 */
  status?: string;
  /** 提示消息 */
  message?: string;
  loginInfo?: UserLoginVO;
}

export interface ResultLoginVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: LoginVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 用户登录响应
 */
export interface UserLoginVO {
  /** 用户token */
  token?: string;
  user?: GetAllUserVO;
}

export interface ResultUserLoginVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: UserLoginVO;
  /** 失败消息 */
  failMsg?: string;
}

export interface VerifyCodeRequestDTO {
  type: string;
  email: string;
}

export interface ResultWorkLogEntity {
  /** 是否成功 */
  isOk?: boolean;
  okData?: WorkLogEntity;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultListWorkLogEntity {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: WorkLogEntity[];
  /** 失败消息 */
  failMsg?: string;
}

export type JSONConfigKeyComparator = { [key: string]: unknown };

export interface JSONConfig {
  keyComparator?: JSONConfigKeyComparator;
  ignoreError?: boolean;
  ignoreCase?: boolean;
  dateFormat?: string;
  ignoreNullValue?: boolean;
  transientSupport?: boolean;
  stripTrailingZeros?: boolean;
  checkDuplicate?: boolean;
  writeLongAsString?: boolean;
  /** @deprecated */
  order?: boolean;
}

export type JSONObjectRaw = { [key: string]: { [key: string]: unknown } };

export interface JSONObject {
  raw?: JSONObjectRaw;
  config?: JSONConfig;
  empty?: boolean;
  [key: string]: { [key: string]: unknown };
}

export interface ResultJSONObject {
  /** 是否成功 */
  isOk?: boolean;
  okData?: JSONObject;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultUserSettingsEntity {
  /** 是否成功 */
  isOk?: boolean;
  okData?: UserSettingsEntity;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultListGetAllUserVO {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: GetAllUserVO[];
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultGetAllUserVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: GetAllUserVO;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultListString {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: string[];
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 景点信息
 */
export interface Attraction {
  /** 景点名称 */
  name?: string;
  /** 景点描述 */
  description?: string;
  /** 景点位置 */
  location?: string;
  /** 最佳游览时间 */
  bestTime?: string;
}

export interface ResultTravelGuideDTO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: TravelGuideDTO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 旅游攻略响应
 */
export interface TravelGuideDTO {
  /** 目的地名称 */
  destination?: string;
  /** 目的地简介 */
  introduction?: string;
  /** 景点列表 */
  attractions?: Attraction[];
  /** 旅游建议 */
  tips?: string;
}

/**
 * 成功数据
 */
export interface GetRandomPhoneVO {
  /** 手机号 */
  phone?: string;
  /** 证件号 */
  idNo?: string;
}

export interface ResultGetRandomPhoneVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: GetRandomPhoneVO;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultSysConfig {
  /** 是否成功 */
  isOk?: boolean;
  okData?: SysConfig;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultListSysConfig {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: SysConfig[];
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 成功数据
 */
export type ResultListMapStringObjectOkDataItem = { [key: string]: { [key: string]: unknown } };

export interface ResultListMapStringObject {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: ResultListMapStringObjectOkDataItem[];
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultListDevTask {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: DevTask[];
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 成功数据
 */
export type ResultMapStringObjectOkData = { [key: string]: { [key: string]: unknown } };

export interface ResultMapStringObject {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: ResultMapStringObjectOkData;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultDailyTask {
  /** 是否成功 */
  isOk?: boolean;
  okData?: DailyTask;
  /** 失败消息 */
  failMsg?: string;
}

export interface ResultListDailyTask {
  /** 是否成功 */
  isOk?: boolean;
  /** 成功数据 */
  okData?: DailyTask[];
  /** 失败消息 */
  failMsg?: string;
}

/**
 * DeepSeek API响应详情
 */
export interface DeepSeekApiResponse {
  /** 响应ID */
  id?: string;
  /** 模型名称 */
  model?: string;
  /** 创建时间 */
  created?: number;
  usage?: TokenUsage;
  /** 完成原因 */
  finishReason?: string;
}

/**
 * 单个优化建议
 */
export interface OptimizationSuggestion {
  /** 优化类型 */
  type?: string;
  /** 优化前内容 */
  before?: string;
  /** 优化后内容 */
  after?: string;
  /** 优化原因 */
  reason?: string;
  /** 优先级 HIGH/MEDIUM/LOW */
  priority?: string;
}

/**
 * AI提示词优化响应
 */
export interface PromptOptimizationResponseVO {
  /** 原始提示词 */
  originalPrompt?: string;
  /** 优化目标 */
  optimizationGoal?: string;
  /** 优化后的提示词 */
  optimizedPrompt?: string;
  /** 优化说明 */
  optimizationExplanation?: string;
  /** 优化建议列表 */
  optimizations?: OptimizationSuggestion[];
  /** 原始AI响应内容 */
  rawResponse?: string;
  /** 保存的Markdown文件相对路径 */
  savedFilePath?: string;
  /** 保存的Markdown文件绝对路径 */
  savedFileAbsolutePath?: string;
  /** 文件保存状态 */
  fileSaved?: boolean;
  /** 生成耗时（毫秒） */
  durationMs?: number;
  /** 生成耗时（秒） */
  durationSeconds?: number;
  /** 邮件发送状态 */
  emailSent?: boolean;
  apiResponse?: DeepSeekApiResponse;
}

export interface ResultPromptOptimizationResponseVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: PromptOptimizationResponseVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * Token使用情况
 */
export interface TokenUsage {
  /** 提示词Token数量 */
  promptTokens?: number;
  /** 生成内容Token数量 */
  completionTokens?: number;
  /** 总Token数量 */
  totalTokens?: number;
}

export interface ResultTableDesignResponseVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: TableDesignResponseVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 表设计DDL响应
 */
export interface TableDesignResponseVO {
  /** 输入的需求描述 */
  inputPrompt?: string;
  /** 生成的DDL语句 */
  ddlSql?: string;
  /** 表名称 */
  tableName?: string;
  /** 表描述 */
  tableDescription?: string;
  /** 字段信息列表 */
  fields?: TableField[];
  /** 索引信息列表 */
  indexes?: TableIndex[];
  /** 外键约束列表 */
  foreignKeys?: string[];
  /** 原始AI响应内容 */
  rawResponse?: string;
  /** 生成耗时（毫秒） */
  durationMs?: number;
  /** 生成耗时（秒） */
  durationSeconds?: number;
  /** 使用的AI模型 */
  model?: string;
  apiResponse?: DeepSeekApiResponse;
}

/**
 * 表字段信息
 */
export interface TableField {
  /** 字段名称 */
  fieldName?: string;
  /** 字段类型 */
  fieldType?: string;
  /** 是否为主键 */
  isPrimaryKey?: boolean;
  /** 是否非空 */
  isNotNull?: boolean;
  /** 字段描述 */
  description?: string;
  /** 是否为审计字段 */
  isAuditField?: boolean;
}

/**
 * 表索引信息
 */
export interface TableIndex {
  /** 索引名称 */
  indexName?: string;
  /** 索引字段 */
  fieldName?: string;
  /** 索引类型 */
  indexType?: string;
  /** 索引注释 */
  description?: string;
}

/**
 * 代码示例
 */
export interface CodeExample {
  /** 示例标题 */
  title?: string;
  /** 代码内容 */
  code?: string;
  /** 示例说明 */
  explanation?: string;
  /** 关键知识点 */
  keyPoints?: string[];
}

/**
 * Hutool工具推荐
 */
export interface HutoolRecommendation {
  /** 工具类名称 */
  toolClass?: string;
  /** 推荐方法 */
  method?: string;
  /** 使用说明 */
  description?: string;
  /** 代码示例 */
  codeExample?: string;
  /** 优势说明 */
  advantage?: string;
}

/**
 * Java开发最佳实践建议响应
 */
export interface JavaBestPracticeResponseVO {
  /** 输入的开发问题描述 */
  inputQuestion?: string;
  /** 问题分类 */
  category?: string;
  /** 分类说明 */
  categoryDescription?: string;
  /** 最佳实践建议列表 */
  suggestions?: PracticeSuggestion[];
  /** Hutool工具推荐 */
  hutoolRecommendations?: HutoolRecommendation[];
  /** 代码示例 */
  codeExamples?: CodeExample[];
  /** 原始AI响应内容 */
  rawResponse?: string;
  /** 保存的Markdown文件相对路径 */
  savedFilePath?: string;
  /** 保存的Markdown文件绝对路径 */
  savedFileAbsolutePath?: string;
  /** 文件保存状态 */
  fileSaved?: boolean;
  /** 生成耗时（毫秒） */
  durationMs?: number;
  /** 生成耗时（秒） */
  durationSeconds?: number;
  /** 邮件发送状态 */
  emailSent?: boolean;
  apiResponse?: DeepSeekApiResponse;
}

/**
 * 实践建议
 */
export interface PracticeSuggestion {
  /** 建议标题 */
  title?: string;
  /** 建议详细描述 */
  description?: string;
  /** 优先级 (HIGH/MEDIUM/LOW) */
  priority?: string;
  /** 适用场景 */
  scenario?: string;
}

export interface ResultJavaBestPracticeResponseVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: JavaBestPracticeResponseVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 单个命名建议
 */
export interface NamingSuggestion {
  /** 推荐的命名 */
  name?: string;
  /** 命名说明（包含含义和选择理由） */
  description?: string;
}

export interface ResultVariableNamingResponseVO {
  /** 是否成功 */
  isOk?: boolean;
  okData?: VariableNamingResponseVO;
  /** 失败消息 */
  failMsg?: string;
}

/**
 * 变量命名响应VO
 */
export interface VariableNamingResponseVO {
  /** 输入的中文描述 */
  inputDescription?: string;
  /** 检测到的命名类型 */
  detectedType?: string;
  /** 检测原因 */
  detectionReason?: string;
  /** 命名建议列表 */
  suggestions?: NamingSuggestion[];
  /** 原始AI文本内容（已从JSON中提取） */
  rawResponse?: string;
  apiResponse?: DeepSeekApiResponse;
}

/**
 * 成功数据
 */
export interface NamingTypeSuggestion {
  type?: string;
  reason?: string;
}

export interface ResultNamingTypeSuggestion {
  /** 是否成功 */
  isOk?: boolean;
  okData?: NamingTypeSuggestion;
  /** 失败消息 */
  failMsg?: string;
}

export type UpdateShowTicketsParams = {
  /**
   * 用户ID
   */
  userId: number;
};

export type UpdateShowTicketsBody = { [key: string]: boolean };

export type UploadFileBody = {
  file: Blob;
};

export type MoveToFinalDirectoryParams = {
  tempFileName: string;
};

export type TestUploadBody = {
  file: Blob;
};

export type GetTravelGuideParams = {
  /**
   * 目的地名称
   */
  destination?: string;
};

export type OpenFileParams = {
  fileName: string;
};

export type GenerateInsertScriptParams = {
  tableName: string;
};

export type GetSignedUrlParams = {
  objectName: string;
};

export type GetPublicUrlParams = {
  objectName: string;
};

export type GetAllTablesParams = {
  schemaName?: string;
};

export type OptimizePromptParams = {
  rawPrompt: string;
  optimizationGoal?: string;
  model?: string;
};

export type GetTableDesignParams = {
  prompt: string;
  model?: string;
};

export type GetRawResponseParams = {
  rowPrompt: string;
  model?: string;
};

export type GetJavaBestPracticesParams = {
  question: string;
  focusArea?: string;
  model?: string;
};

export type GetNameSuggestionParams = {
  description: string;
  type?: string;
  model?: string;
};

export type DetectNamingTypeParams = {
  description: string;
};

export type TestDeleteParams = {
  objectName: string;
};
