/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  CmdBoolean,
  CmdListRequirementEntity,
  CmdRequirementEntity,
  RequirementEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getRequirement = () => {
  /**
   * @summary 更新
   */
  const requirementUpdate = (requirementEntity: RequirementEntity) => {
    return customInstance<CmdBoolean>({
      url: `/api/requirement`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: requirementEntity,
    });
  };
  /**
   * @summary 新增
   */
  const requirementCreate = (requirementEntity: RequirementEntity) => {
    return customInstance<CmdBoolean>({
      url: `/api/requirement`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: requirementEntity,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const requirementGetById = (id: number) => {
    return customInstance<CmdRequirementEntity>({ url: `/api/requirement/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除
   */
  const requirementDelete = (id: number) => {
    return customInstance<CmdBoolean>({ url: `/api/requirement/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取当前用户的需求
   */
  const requirementMe = () => {
    return customInstance<CmdListRequirementEntity>({
      url: `/api/requirement/list`,
      method: 'GET',
    });
  };
  return {
    requirementUpdate,
    requirementCreate,
    requirementGetById,
    requirementDelete,
    requirementMe,
  };
};
export type RequirementUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['requirementUpdate']>>
>;
export type RequirementCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['requirementCreate']>>
>;
export type RequirementGetByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['requirementGetById']>>
>;
export type RequirementDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['requirementDelete']>>
>;
export type RequirementMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['requirementMe']>>
>;
