/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type {
  ResultBoolean,
  ResultListRequirementEntity,
  ResultListString,
  ResultRequirementEntity,
} from '../api.schemas';

export const getUpdateRequirementResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getSaveRequirementResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getGetRequirementByIdResponseMock = (
  overrideResponse: Partial<ResultRequirementEntity> = {},
): ResultRequirementEntity => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      requirementId: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      requirementName: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      relatedRequirementDocs: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      relatedDesignDocs: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      systemCategory: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getDeleteRequirementResponseMock = (
  overrideResponse: Partial<ResultBoolean> = {},
): ResultBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getGetAllRequirementNamesResponseMock = (
  overrideResponse: Partial<ResultListString> = {},
): ResultListString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha(20),
    ),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetCurrentUserRequirementResponseMock = (
  overrideResponse: Partial<ResultListRequirementEntity> = {},
): ResultListRequirementEntity => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      requirementId: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      requirementName: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      relatedRequirementDocs: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      relatedDesignDocs: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      systemCategory: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getUpdateRequirementMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.put('*/api/requirement', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUpdateRequirementResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSaveRequirementMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.post('*/api/requirement', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSaveRequirementResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetRequirementByIdMockHandler = (
  overrideResponse?:
    | ResultRequirementEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultRequirementEntity> | ResultRequirementEntity),
) => {
  return http.get('*/api/requirement/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetRequirementByIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getDeleteRequirementMockHandler = (
  overrideResponse?:
    | ResultBoolean
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ResultBoolean> | ResultBoolean),
) => {
  return http.delete('*/api/requirement/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDeleteRequirementResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetAllRequirementNamesMockHandler = (
  overrideResponse?:
    | ResultListString
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultListString> | ResultListString),
) => {
  return http.get('*/api/requirement/name-all', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetAllRequirementNamesResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetCurrentUserRequirementMockHandler = (
  overrideResponse?:
    | ResultListRequirementEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultListRequirementEntity> | ResultListRequirementEntity),
) => {
  return http.get('*/api/requirement/list', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCurrentUserRequirementResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getRequirementMock = () => [
  getUpdateRequirementMockHandler(),
  getSaveRequirementMockHandler(),
  getGetRequirementByIdMockHandler(),
  getDeleteRequirementMockHandler(),
  getGetAllRequirementNamesMockHandler(),
  getGetCurrentUserRequirementMockHandler(),
];
