/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  RequirementEntity,
  ResultBoolean,
  ResultListRequirementEntity,
  ResultListString,
  ResultRequirementEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getRequirement = () => {
  /**
   * @summary 更新
   */
  const updateRequirement = (requirementEntity: RequirementEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/requirement`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: requirementEntity,
    });
  };
  /**
   * @summary 新增
   */
  const saveRequirement = (requirementEntity: RequirementEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/requirement`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: requirementEntity,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const getRequirementById = (id: number) => {
    return customInstance<ResultRequirementEntity>({
      url: `/api/requirement/${id}`,
      method: 'GET',
    });
  };
  /**
   * @summary 删除
   */
  const deleteRequirement = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/requirement/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取所有需求的名称
   */
  const getAllRequirementNames = () => {
    return customInstance<ResultListString>({ url: `/api/requirement/name-all`, method: 'GET' });
  };
  /**
   * @summary 获取当前用户的需求
   */
  const getCurrentUserRequirement = () => {
    return customInstance<ResultListRequirementEntity>({
      url: `/api/requirement/list`,
      method: 'GET',
    });
  };
  return {
    updateRequirement,
    saveRequirement,
    getRequirementById,
    deleteRequirement,
    getAllRequirementNames,
    getCurrentUserRequirement,
  };
};
export type UpdateRequirementResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['updateRequirement']>>
>;
export type SaveRequirementResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['saveRequirement']>>
>;
export type GetRequirementByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['getRequirementById']>>
>;
export type DeleteRequirementResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['deleteRequirement']>>
>;
export type GetAllRequirementNamesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['getAllRequirementNames']>>
>;
export type GetCurrentUserRequirementResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRequirement>['getCurrentUserRequirement']>>
>;
