/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultString, SubscriptionRequestDTO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getNotification = () => {
  /**
   * @summary 订阅通知
   */
  const notificationSubscribe = (subscriptionRequestDTO: SubscriptionRequestDTO) => {
    return customInstance<ResultString>({
      url: `/api/notification/subscribe`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: subscriptionRequestDTO,
    });
  };
  /**
   * @summary 推送通知
   */
  const notificationPush = (subscriptionRequestDTO: SubscriptionRequestDTO) => {
    return customInstance<ResultString>({
      url: `/api/notification/push`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: subscriptionRequestDTO,
    });
  };
  return { notificationSubscribe, notificationPush };
};
export type NotificationSubscribeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getNotification>['notificationSubscribe']>>
>;
export type NotificationPushResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getNotification>['notificationPush']>>
>;
