/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultWeatherResponseDTO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getWeather = () => {
  /**
   * @summary 获取天气信息
   */
  const weatherInfo = () => {
    return customInstance<ResultWeatherResponseDTO>({ url: `/api/weather`, method: 'GET' });
  };
  return { weatherInfo };
};
export type WeatherInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWeather>['weatherInfo']>>
>;
