/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultJSONObject } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getWeather = () => {
  /**
   * @summary 获取未来3天天气
   */
  const get3dWeather = () => {
    return customInstance<ResultJSONObject>({ url: `/api/weather/3d`, method: 'GET' });
  };
  return { get3dWeather };
};
export type Get3dWeatherResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWeather>['get3dWeather']>>
>;
