/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { ResultWeatherResponseDTO } from '../api.schemas';

export const getWeatherInfoResponseMock = (
  overrideResponse: Partial<ResultWeatherResponseDTO> = {},
): ResultWeatherResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      updateTime: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      fxLink: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      now: faker.helpers.arrayElement([
        {
          obsTime: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          temp: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          feelsLike: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          icon: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          text: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          wind360: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          windDir: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          windScale: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          windSpeed: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          humidity: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          precip: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          pressure: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          vis: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          cloud: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
          dew: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
        },
        undefined,
      ]),
      refer: faker.helpers.arrayElement([
        {
          sources: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          license: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
        },
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getWeatherInfoMockHandler = (
  overrideResponse?:
    | ResultWeatherResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultWeatherResponseDTO> | ResultWeatherResponseDTO),
) => {
  return http.get('*/api/weather', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getWeatherInfoResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getWeatherMock = () => [getWeatherInfoMockHandler()];
