/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  ResultBoolean,
  ResultListTodoEntity,
  ResultTodoEntity,
  TodoEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getTodo = () => {
  /**
   * @summary 更新待办事项
   */
  const updateTodo = (todoEntity: TodoEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/todo`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: todoEntity,
    });
  };
  /**
   * @summary 新增待办事项
   */
  const saveTodo = (todoEntity: TodoEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/todo`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: todoEntity,
    });
  };
  /**
   * @summary 标记待办事项为已完成
   */
  const completeTodo = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/todo/${id}/complete`, method: 'PUT' });
  };
  /**
   * @summary 根据ID获取待办事项
   */
  const getTodoById = (id: number) => {
    return customInstance<ResultTodoEntity>({ url: `/api/todo/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除待办事项
   */
  const deleteTodo = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/todo/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取当前用户的待办事项列表
   */
  const listTodoOfMe = () => {
    return customInstance<ResultListTodoEntity>({ url: `/api/todo/list`, method: 'GET' });
  };
  /**
   * @summary 按类别获取待办事项
   */
  const listTodoByCategory = (category: string) => {
    return customInstance<ResultListTodoEntity>({
      url: `/api/todo/by-category/${category}`,
      method: 'GET',
    });
  };
  return {
    updateTodo,
    saveTodo,
    completeTodo,
    getTodoById,
    deleteTodo,
    listTodoOfMe,
    listTodoByCategory,
  };
};
export type UpdateTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['updateTodo']>>
>;
export type SaveTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['saveTodo']>>
>;
export type CompleteTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['completeTodo']>>
>;
export type GetTodoByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['getTodoById']>>
>;
export type DeleteTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['deleteTodo']>>
>;
export type ListTodoOfMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['listTodoOfMe']>>
>;
export type ListTodoByCategoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['listTodoByCategory']>>
>;
