/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  ResultBoolean,
  ResultListTodoVO,
  ResultObject,
  ResultString,
  ResultTodo,
  Todo,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getTodo = () => {
  /**
   * @summary 根据ID获取待办事项
   */
  const getTodoById = (id: string) => {
    return customInstance<ResultTodo>({ url: `/api/todo/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除待办事项
   */
  const deleteTodo = (id: string) => {
    return customInstance<ResultString>({ url: `/api/todo/${id}`, method: 'POST' });
  };
  /**
   * @summary 标记待办事项为已完成
   */
  const completeTodo = (id: number) => {
    return customInstance<ResultObject>({ url: `/api/todo/${id}/complete`, method: 'POST' });
  };
  /**
   * @summary 更新待办事项
   */
  const updateTodo = (todo: Todo) => {
    return customInstance<ResultBoolean>({
      url: `/api/todo/update`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: todo,
    });
  };
  /**
   * @summary 新增待办事项
   */
  const saveTodo = (todo: Todo) => {
    return customInstance<ResultTodo>({
      url: `/api/todo/save`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: todo,
    });
  };
  /**
   * @summary 获取当前用户的待办
   */
  const listTodoOfMe = () => {
    return customInstance<ResultListTodoVO>({ url: `/api/todo/list`, method: 'GET' });
  };
  /**
   * @summary 按类别获取待办事项
   */
  const listTodoByCategory = (category: string) => {
    return customInstance<ResultListTodoVO>({
      url: `/api/todo/by-category/${category}`,
      method: 'GET',
    });
  };
  return {
    getTodoById,
    deleteTodo,
    completeTodo,
    updateTodo,
    saveTodo,
    listTodoOfMe,
    listTodoByCategory,
  };
};
export type GetTodoByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['getTodoById']>>
>;
export type DeleteTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['deleteTodo']>>
>;
export type CompleteTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['completeTodo']>>
>;
export type UpdateTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['updateTodo']>>
>;
export type SaveTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['saveTodo']>>
>;
export type ListTodoOfMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['listTodoOfMe']>>
>;
export type ListTodoByCategoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['listTodoByCategory']>>
>;
