/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  GetTodoByConditionInParam,
  ResultBoolean,
  ResultListTodoVO,
  ResultString,
  ResultTodo,
  Todo,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getTodo = () => {
  /**
   * @summary 根据条件来查询待办
   */
  const getTodoByCondition = (getTodoByConditionInParam: GetTodoByConditionInParam) => {
    return customInstance<ResultListTodoVO>({
      url: `/api/url/getTodoByCondition`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getTodoByConditionInParam,
    });
  };
  /**
   * @summary 删除待办
   */
  const deleteTodo = (id: string) => {
    return customInstance<ResultString>({ url: `/api/todo/${id}/deleteTodo`, method: 'POST' });
  };
  /**
   * @summary 标记待办为已完成
   */
  const completeTodo = (id: string) => {
    return customInstance<ResultString>({ url: `/api/todo/${id}/completeTodo`, method: 'POST' });
  };
  /**
   * @summary 更新待办
   */
  const updateTodo = (todo: Todo) => {
    return customInstance<ResultBoolean>({
      url: `/api/todo/updateTodo`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: todo,
    });
  };
  /**
   * @summary 新增待办
   */
  const saveTodo = (todo: Todo) => {
    return customInstance<ResultTodo>({
      url: `/api/todo/saveTodo`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: todo,
    });
  };
  return { getTodoByCondition, deleteTodo, completeTodo, updateTodo, saveTodo };
};
export type GetTodoByConditionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['getTodoByCondition']>>
>;
export type DeleteTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['deleteTodo']>>
>;
export type CompleteTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['completeTodo']>>
>;
export type UpdateTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['updateTodo']>>
>;
export type SaveTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTodo>['saveTodo']>>
>;
