/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  ResultListWifiOperationResultVO,
  ResultWifiOperationResultVO,
  WifiConnectRequestDTO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getWifi = () => {
  /**
   * @summary 删除保存的WIFI配置
   */
  const forgetWifi = (ssid: string) => {
    return customInstance<ResultWifiOperationResultVO>({
      url: `/api/wifi/forget/${ssid}`,
      method: 'POST',
    });
  };
  /**
   * @summary 断开当前WIFI连接
   */
  const disconnectWifi = () => {
    return customInstance<ResultWifiOperationResultVO>({
      url: `/api/wifi/disconnect`,
      method: 'POST',
    });
  };
  /**
   * @summary 连接WIFI网络
   */
  const connectWifi = (wifiConnectRequestDTO: WifiConnectRequestDTO) => {
    return customInstance<ResultWifiOperationResultVO>({
      url: `/api/wifi/connect`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: wifiConnectRequestDTO,
    });
  };
  /**
   * @summary 获取当前WIFI连接状态
   */
  const getCurrentWifiStatus = () => {
    return customInstance<ResultWifiOperationResultVO>({ url: `/api/wifi/status`, method: 'GET' });
  };
  /**
   * @summary 扫描可用的WIFI网络
   */
  const scanWifiNetworks = () => {
    return customInstance<ResultListWifiOperationResultVO>({
      url: `/api/wifi/scan`,
      method: 'GET',
    });
  };
  return { forgetWifi, disconnectWifi, connectWifi, getCurrentWifiStatus, scanWifiNetworks };
};
export type ForgetWifiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWifi>['forgetWifi']>>
>;
export type DisconnectWifiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWifi>['disconnectWifi']>>
>;
export type ConnectWifiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWifi>['connectWifi']>>
>;
export type GetCurrentWifiStatusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWifi>['getCurrentWifiStatus']>>
>;
export type ScanWifiNetworksResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWifi>['scanWifiNetworks']>>
>;
