/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultString } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getClear = () => {
  /**
   * @summary 系统文件
   */
  const clearSysFile = () => {
    return customInstance<ResultString>({ url: `/api/clear/sysFile`, method: 'POST' });
  };
  /**
   * @summary 开发任务
   */
  const clearDevTask = () => {
    return customInstance<ResultString>({ url: `/api/clear/devTask`, method: 'POST' });
  };
  return { clearSysFile, clearDevTask };
};
export type ClearSysFileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getClear>['clearSysFile']>>
>;
export type ClearDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getClear>['clearDevTask']>>
>;
