/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  ResultBoolean,
  ResultListWorkLogEntity,
  ResultWorkLogEntity,
  WorkLogEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getWorkLog = () => {
  /**
   * @summary 更新
   */
  const updateWorkLog = (workLogEntity: WorkLogEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/work-log`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: workLogEntity,
    });
  };
  /**
   * @summary 新增
   */
  const saveWorkLog = (workLogEntity: WorkLogEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/work-log`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: workLogEntity,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const getWorkLogById = (id: number) => {
    return customInstance<ResultWorkLogEntity>({ url: `/api/work-log/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除
   */
  const deleteWorkLog = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/work-log/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取当前用户的工作日志
   */
  const listWorkLogOfMe = () => {
    return customInstance<ResultListWorkLogEntity>({ url: `/api/work-log/list`, method: 'GET' });
  };
  return { updateWorkLog, saveWorkLog, getWorkLogById, deleteWorkLog, listWorkLogOfMe };
};
export type UpdateWorkLogResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWorkLog>['updateWorkLog']>>
>;
export type SaveWorkLogResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWorkLog>['saveWorkLog']>>
>;
export type GetWorkLogByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWorkLog>['getWorkLogById']>>
>;
export type DeleteWorkLogResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWorkLog>['deleteWorkLog']>>
>;
export type ListWorkLogOfMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWorkLog>['listWorkLogOfMe']>>
>;
