/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  ResultBoolean,
  ResultListSystemConfigEntity,
  ResultSystemConfigEntity,
  SystemConfigEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getSystemConfig = () => {
  /**
   * @summary 更新
   */
  const systemConfigUpdate = (systemConfigEntity: SystemConfigEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/systemConfig`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: systemConfigEntity,
    });
  };
  /**
   * @summary 新增
   */
  const systemConfigCreate = (systemConfigEntity: SystemConfigEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/systemConfig`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: systemConfigEntity,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const systemConfigGetById = (id: number) => {
    return customInstance<ResultSystemConfigEntity>({
      url: `/api/systemConfig/${id}`,
      method: 'GET',
    });
  };
  /**
   * @summary 删除
   */
  const systemConfigDelete = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/systemConfig/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取所有系统配置
   */
  const systemConfigList = () => {
    return customInstance<ResultListSystemConfigEntity>({
      url: `/api/systemConfig/list`,
      method: 'GET',
    });
  };
  return {
    systemConfigUpdate,
    systemConfigCreate,
    systemConfigGetById,
    systemConfigDelete,
    systemConfigList,
  };
};
export type SystemConfigUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSystemConfig>['systemConfigUpdate']>>
>;
export type SystemConfigCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSystemConfig>['systemConfigCreate']>>
>;
export type SystemConfigGetByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSystemConfig>['systemConfigGetById']>>
>;
export type SystemConfigDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSystemConfig>['systemConfigDelete']>>
>;
export type SystemConfigListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSystemConfig>['systemConfigList']>>
>;
