/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdBoolean, CmdListSystemConfigEntity, CmdSystemConfigEntity } from '../api.schemas';

export const getSystemConfigUpdateResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getSystemConfigCreateResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getSystemConfigGetByIdResponseMock = (
  overrideResponse: Partial<CmdSystemConfigEntity> = {},
): CmdSystemConfigEntity => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      configKey: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      configValue: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      description: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      groupName: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      enabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getSystemConfigDeleteResponseMock = (
  overrideResponse: Partial<CmdBoolean> = {},
): CmdBoolean => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getSystemConfigListResponseMock = (
  overrideResponse: Partial<CmdListSystemConfigEntity> = {},
): CmdListSystemConfigEntity => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      updatedBy: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      updatedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      configKey: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      configValue: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      description: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      groupName: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      enabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getSystemConfigUpdateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.put('*/api/systemConfig', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSystemConfigUpdateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSystemConfigCreateMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.post('*/api/systemConfig', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSystemConfigCreateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSystemConfigGetByIdMockHandler = (
  overrideResponse?:
    | CmdSystemConfigEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdSystemConfigEntity> | CmdSystemConfigEntity),
) => {
  return http.get('*/api/systemConfig/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSystemConfigGetByIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSystemConfigDeleteMockHandler = (
  overrideResponse?:
    | CmdBoolean
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CmdBoolean> | CmdBoolean),
) => {
  return http.delete('*/api/systemConfig/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSystemConfigDeleteResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSystemConfigListMockHandler = (
  overrideResponse?:
    | CmdListSystemConfigEntity
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CmdListSystemConfigEntity> | CmdListSystemConfigEntity),
) => {
  return http.get('*/api/systemConfig/list', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSystemConfigListResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getSystemConfigMock = () => [
  getSystemConfigUpdateMockHandler(),
  getSystemConfigCreateMockHandler(),
  getSystemConfigGetByIdMockHandler(),
  getSystemConfigDeleteMockHandler(),
  getSystemConfigListMockHandler(),
];
