/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultSysFile, SysFile } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getSysFile = () => {
  /**
   * @summary 新增系统文件
   */
  const saveSysFile = (sysFile: SysFile) => {
    return customInstance<ResultSysFile>({
      url: `/api/sysFile/saveSysFile`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sysFile,
    });
  };
  return { saveSysFile };
};
export type SaveSysFileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysFile>['saveSysFile']>>
>;
