/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { GenerateInsertScriptParams, ResultString } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getSql = () => {
  /**
   * @summary 查询指定表的数据并生成insert脚本
   */
  const generateInsertScript = (params: GenerateInsertScriptParams) => {
    return customInstance<ResultString>({
      url: `/api/sql/generateInsertScript`,
      method: 'GET',
      params,
    });
  };
  return { generateInsertScript };
};
export type GenerateInsertScriptResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSql>['generateInsertScript']>>
>;
