/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  QueryDevTaskInParam,
  ResultDevTask,
  ResultIPageDevTaskVO,
  ResultListString,
  ResultMapStringObject,
  ResultString,
  SaveDevTaskInParam,
  UpdateDevTaskInParam,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDevTask = () => {
  /**
   * @summary 删除开发任务
   */
  const deleteDevTask = (id: string) => {
    return customInstance<ResultString>({
      url: `/api/devTask/${id}/deleteDevTask`,
      method: 'POST',
    });
  };
  /**
   * @summary 更新开发任务
   */
  const updateDevTask = (updateDevTaskInParam: UpdateDevTaskInParam) => {
    return customInstance<ResultDevTask>({
      url: `/api/devTask/updateDevTask`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateDevTaskInParam,
    });
  };
  /**
   * @summary 新增开发任务
   */
  const saveDevTask = (saveDevTaskInParam: SaveDevTaskInParam) => {
    return customInstance<ResultDevTask>({
      url: `/api/devTask/saveDevTask`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: saveDevTaskInParam,
    });
  };
  /**
   * @summary 分页查询开发任务
   */
  const queryDevTask = (queryDevTaskInParam: QueryDevTaskInParam) => {
    return customInstance<ResultIPageDevTaskVO>({
      url: `/api/devTask/queryDevTask`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: queryDevTaskInParam,
    });
  };
  /**
   * @summary 获取所有需求的名称
   */
  const getAllDevTaskNames = () => {
    return customInstance<ResultListString>({ url: `/api/devTask/name-all`, method: 'GET' });
  };
  /**
   * @summary 备份DevTask表数据
   */
  const backupDevTask = () => {
    return customInstance<ResultMapStringObject>({ url: `/api/devTask/backup`, method: 'GET' });
  };
  /**
   * @summary 下载DevTask备份文件
   */
  const downloadBackup = () => {
    return customInstance<void>({ url: `/api/devTask/backup/download`, method: 'GET' });
  };
  return {
    deleteDevTask,
    updateDevTask,
    saveDevTask,
    queryDevTask,
    getAllDevTaskNames,
    backupDevTask,
    downloadBackup,
  };
};
export type DeleteDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['deleteDevTask']>>
>;
export type UpdateDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['updateDevTask']>>
>;
export type SaveDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['saveDevTask']>>
>;
export type QueryDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['queryDevTask']>>
>;
export type GetAllDevTaskNamesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['getAllDevTaskNames']>>
>;
export type BackupDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['backupDevTask']>>
>;
export type DownloadBackupResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['downloadBackup']>>
>;
