/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  DevTask,
  QueryDevTaskInParam,
  ResultBoolean,
  ResultDevTask,
  ResultIPageDevTask,
  ResultListDevTask,
  ResultListString,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getDevTask = () => {
  /**
   * @summary 新增
   */
  const saveDevTask = (devTask: DevTask) => {
    return customInstance<ResultBoolean>({
      url: `/api/devTask/saveDevTask`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: devTask,
    });
  };
  /**
   * @summary 分页查询开发任务
   */
  const queryDevTask = (queryDevTaskInParam: QueryDevTaskInParam) => {
    return customInstance<ResultIPageDevTask>({
      url: `/api/devTask/queryDevTask`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: queryDevTaskInParam,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const getDevTaskById = (id: string) => {
    return customInstance<ResultDevTask>({
      url: `/api/devTask/${id}/getDevTaskById`,
      method: 'GET',
    });
  };
  /**
   * @summary 获取所有需求的名称
   */
  const getAllDevTaskNames = () => {
    return customInstance<ResultListString>({ url: `/api/devTask/name-all`, method: 'GET' });
  };
  /**
   * @summary 获取当前用户的需求
   */
  const getCurrentUserRequirement = () => {
    return customInstance<ResultListDevTask>({ url: `/api/devTask/getMyDevTask`, method: 'GET' });
  };
  return {
    saveDevTask,
    queryDevTask,
    getDevTaskById,
    getAllDevTaskNames,
    getCurrentUserRequirement,
  };
};
export type SaveDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['saveDevTask']>>
>;
export type QueryDevTaskResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['queryDevTask']>>
>;
export type GetDevTaskByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['getDevTaskById']>>
>;
export type GetAllDevTaskNamesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['getAllDevTaskNames']>>
>;
export type GetCurrentUserRequirementResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDevTask>['getCurrentUserRequirement']>>
>;
