/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  GetUrlByConditionInParam,
  ResultBoolean,
  ResultListSysUrl,
  SysUrl,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getUrl = () => {
  /**
   * @summary 删除URL
   */
  const deleteUrl = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/url/${id}`, method: 'POST' });
  };
  /**
   * @summary 根据条件来查询URL
   */
  const getUrlByCondition = (getUrlByConditionInParam: GetUrlByConditionInParam) => {
    return customInstance<ResultListSysUrl>({
      url: `/api/url/getUrlByCondition`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getUrlByConditionInParam,
    });
  };
  /**
   * @summary 修改URL
   */
  const updateUrl = (sysUrl: SysUrl) => {
    return customInstance<ResultBoolean>({
      url: `/api/updateUrl`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sysUrl,
    });
  };
  /**
   * @summary 新增URL
   */
  const saveUrl = (sysUrl: SysUrl) => {
    return customInstance<ResultBoolean>({
      url: `/api/saveUrl`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sysUrl,
    });
  };
  /**
   * @summary 获取当前用户的URL列表
   */
  const listUrlOfMe = () => {
    return customInstance<ResultListSysUrl>({ url: `/api/url/list`, method: 'GET' });
  };
  return { deleteUrl, getUrlByCondition, updateUrl, saveUrl, listUrlOfMe };
};
export type DeleteUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['deleteUrl']>>
>;
export type GetUrlByConditionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['getUrlByCondition']>>
>;
export type UpdateUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['updateUrl']>>
>;
export type SaveUrlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrl>['saveUrl']>>>;
export type ListUrlOfMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['listUrlOfMe']>>
>;
