/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  ResultBoolean,
  ResultListUrlEntity,
  ResultUrlEntity,
  UrlEntity,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getUrl = () => {
  /**
   * @summary 更新URL
   */
  const updateUrl = (urlEntity: UrlEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/url`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: urlEntity,
    });
  };
  /**
   * @summary 新增URL
   */
  const saveUrl = (urlEntity: UrlEntity) => {
    return customInstance<ResultBoolean>({
      url: `/api/url`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: urlEntity,
    });
  };
  /**
   * @summary 根据ID获取URL
   */
  const getUrlById = (id: number) => {
    return customInstance<ResultUrlEntity>({ url: `/api/url/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除URL
   */
  const deleteUrl = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/url/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取当前用户的URL列表
   */
  const listUrlOfMe = () => {
    return customInstance<ResultListUrlEntity>({ url: `/api/url/list`, method: 'GET' });
  };
  return { updateUrl, saveUrl, getUrlById, deleteUrl, listUrlOfMe };
};
export type UpdateUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['updateUrl']>>
>;
export type SaveUrlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrl>['saveUrl']>>>;
export type GetUrlByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['getUrlById']>>
>;
export type DeleteUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['deleteUrl']>>
>;
export type ListUrlOfMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['listUrlOfMe']>>
>;
