/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  GetUrlByConditionInParam,
  ResultListString,
  ResultListSysUrl,
  ResultString,
  ResultSysUrl,
  SaveUrlInParam,
  UpdateUrlCategoryInParam,
  UpdateUrlInParam,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getUrl = () => {
  /**
   * @summary 删除URL
   */
  const deleteUrl = (id: string) => {
    return customInstance<ResultString>({ url: `/api/url/${id}/deleteUrl`, method: 'POST' });
  };
  /**
   * @summary 修改URL
   */
  const updateUrl = (updateUrlInParam: UpdateUrlInParam) => {
    return customInstance<ResultSysUrl>({
      url: `/api/url/updateUrl`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateUrlInParam,
    });
  };
  /**
   * @summary 批量更改URL目录分类
   */
  const updateUrlCategory = (updateUrlCategoryInParam: UpdateUrlCategoryInParam) => {
    return customInstance<ResultString>({
      url: `/api/url/updateUrlCategory`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateUrlCategoryInParam,
    });
  };
  /**
   * @summary 新增URL
   */
  const saveUrl = (saveUrlInParam: SaveUrlInParam) => {
    return customInstance<ResultSysUrl>({
      url: `/api/url/saveUrl`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: saveUrlInParam,
    });
  };
  /**
   * @summary 根据条件来查询URL
   */
  const getUrlByCondition = (getUrlByConditionInParam: GetUrlByConditionInParam) => {
    return customInstance<ResultListSysUrl>({
      url: `/api/url/getUrlByCondition`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getUrlByConditionInParam,
    });
  };
  /**
   * @summary 获取URL的分类
   */
  const getUrlTag = () => {
    return customInstance<ResultListString>({ url: `/api/url/getUrlTag`, method: 'GET' });
  };
  return { deleteUrl, updateUrl, updateUrlCategory, saveUrl, getUrlByCondition, getUrlTag };
};
export type DeleteUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['deleteUrl']>>
>;
export type UpdateUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['updateUrl']>>
>;
export type UpdateUrlCategoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['updateUrlCategory']>>
>;
export type SaveUrlResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrl>['saveUrl']>>>;
export type GetUrlByConditionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['getUrlByCondition']>>
>;
export type GetUrlTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUrl>['getUrlTag']>>
>;
