/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  GetPublicUrlParams,
  GetSignedUrlParams,
  ResultString,
  TestDeleteParams,
  TestUploadBody,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getOssTest = () => {
  const testUpload = (directory: string, testUploadBody: TestUploadBody) => {
    return customInstance<ResultString>({
      url: `/api/oss-test/upload/${directory}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: testUploadBody,
    });
  };
  const getSignedUrl = (params: GetSignedUrlParams) => {
    return customInstance<ResultString>({ url: `/api/oss-test/url`, method: 'GET', params });
  };
  const getPublicUrl = (params: GetPublicUrlParams) => {
    return customInstance<ResultString>({ url: `/api/oss-test/public-url`, method: 'GET', params });
  };
  const testDelete = (params: TestDeleteParams) => {
    return customInstance<ResultString>({ url: `/api/oss-test/delete`, method: 'DELETE', params });
  };
  return { testUpload, getSignedUrl, getPublicUrl, testDelete };
};
export type TestUploadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOssTest>['testUpload']>>
>;
export type GetSignedUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOssTest>['getSignedUrl']>>
>;
export type GetPublicUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOssTest>['getPublicUrl']>>
>;
export type TestDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOssTest>['testDelete']>>
>;
