/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * 露游记 API文档
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';

import type { CmdString } from '../api.schemas';

export const getTestUploadResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getGetSignedUrlResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getGetPublicUrlResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getTestDeleteResponseMock = (
  overrideResponse: Partial<CmdString> = {},
): CmdString => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  payload: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  ...overrideResponse,
});

export const getTestUploadMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.post('*/api/oss-test/upload/:directory', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getTestUploadResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetSignedUrlMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.get('*/api/oss-test/url', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetSignedUrlResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetPublicUrlMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.get('*/api/oss-test/public-url', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPublicUrlResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getTestDeleteMockHandler = (
  overrideResponse?:
    | CmdString
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<CmdString> | CmdString),
) => {
  return http.delete('*/api/oss-test/delete', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getTestDeleteResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getOssTestMock = () => [
  getTestUploadMockHandler(),
  getGetSignedUrlMockHandler(),
  getGetPublicUrlMockHandler(),
  getTestDeleteMockHandler(),
];
