/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  ResultBoolean,
  ResultListSysConfig,
  ResultSysConfig,
  SysConfig,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getSysConfig = () => {
  /**
   * @summary 更新
   */
  const update1 = (sysConfig: SysConfig) => {
    return customInstance<ResultBoolean>({
      url: `/api/sys_config`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: sysConfig,
    });
  };
  /**
   * @summary 新增
   */
  const save1 = (sysConfig: SysConfig) => {
    return customInstance<ResultBoolean>({
      url: `/api/sys_config`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sysConfig,
    });
  };
  /**
   * @summary 根据ID获取
   */
  const getById1 = (id: number) => {
    return customInstance<ResultSysConfig>({ url: `/api/sys_config/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除
   */
  const delete1 = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/sys_config/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取所有系统配置
   */
  const getAllConfig = () => {
    return customInstance<ResultListSysConfig>({
      url: `/api/sys_config/getAllConfig`,
      method: 'GET',
    });
  };
  return { update1, save1, getById1, delete1, getAllConfig };
};
export type Update1Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysConfig>['update1']>>
>;
export type Save1Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysConfig>['save1']>>
>;
export type GetById1Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysConfig>['getById1']>>
>;
export type Delete1Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysConfig>['delete1']>>
>;
export type GetAllConfigResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysConfig>['getAllConfig']>>
>;
