/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultListEnumVO } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getEnum = () => {
  /**
   * @summary 根据枚举名称获取枚举选项列表
   */
  const getEnumOptions = (enumName: string) => {
    return customInstance<ResultListEnumVO>({ url: `/api/enum/${enumName}`, method: 'GET' });
  };
  return { getEnumOptions };
};
export type GetEnumOptionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEnum>['getEnumOptions']>>
>;
