/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type { ResultListMapStringObject } from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getEnum = () => {
  /**
   * @summary 根据枚举名称获取枚举选项列表
   */
  const getEnumByName = (enumName: string) => {
    return customInstance<ResultListMapStringObject>({
      url: `/api/enum/${enumName}/getEnumByName`,
      method: 'GET',
    });
  };
  return { getEnumByName };
};
export type GetEnumByNameResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEnum>['getEnumByName']>>
>;
