/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  RecognizeSignalParamsBody,
  RecognizeSignalParamsParams,
  ResultBoolean,
  ResultListSignalParamsVO,
  ResultSignalParamsVO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getRfSignalParams = () => {
  /**
   * @summary 删除射频信号参数记录
   */
  const deleteSignalParams = (id: number) => {
    return customInstance<ResultBoolean>({
      url: `/api/signal/${id}/delSignalParams`,
      method: 'POST',
    });
  };
  /**
   * @summary 识别射频信号参数图片
   */
  const recognizeSignalParams = (
    recognizeSignalParamsBody: RecognizeSignalParamsBody,
    params?: RecognizeSignalParamsParams,
  ) => {
    const formData = new FormData();
    formData.append(`imageFile`, recognizeSignalParamsBody.imageFile);

    return customInstance<ResultSignalParamsVO>({
      url: `/api/signal/recognize`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      params,
    });
  };
  /**
   * @summary 获取所有射频信号参数列表
   */
  const querySignalParam = () => {
    return customInstance<ResultListSignalParamsVO>({
      url: `/api/signal/querySignalParam`,
      method: 'POST',
    });
  };
  /**
   * @summary 根据ID查询射频信号参数
   */
  const getSignalParamsById = (id: number) => {
    return customInstance<ResultSignalParamsVO>({
      url: `/api/signal/${id}/getByID`,
      method: 'GET',
    });
  };
  return { deleteSignalParams, recognizeSignalParams, querySignalParam, getSignalParamsById };
};
export type DeleteSignalParamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['deleteSignalParams']>>
>;
export type RecognizeSignalParamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['recognizeSignalParams']>>
>;
export type QuerySignalParamResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['querySignalParam']>>
>;
export type GetSignalParamsByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['getSignalParamsById']>>
>;
