/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API清单
 * 前端提供UI，后端提供API
 * OpenAPI spec version: 1.0
 */
import type {
  RecognizeSignalParamsBody,
  RecognizeSignalParamsParams,
  ResultBoolean,
  ResultListSignalParamsVO,
  ResultSignalParamsVO,
} from '../api.schemas';

import { customInstance } from '../../boot/orval-client';

export const getRfSignalParams = () => {
  /**
   * @summary 识别射频信号参数图片
   */
  const recognizeSignalParams = (
    recognizeSignalParamsBody: RecognizeSignalParamsBody,
    params?: RecognizeSignalParamsParams,
  ) => {
    return customInstance<ResultSignalParamsVO>({
      url: `/api/signal/recognize`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: recognizeSignalParamsBody,
      params,
    });
  };
  /**
   * @summary 根据ID查询射频信号参数
   */
  const getSignalParamsById = (id: number) => {
    return customInstance<ResultSignalParamsVO>({ url: `/api/signal/${id}`, method: 'GET' });
  };
  /**
   * @summary 删除射频信号参数记录
   */
  const deleteSignalParams = (id: number) => {
    return customInstance<ResultBoolean>({ url: `/api/signal/${id}`, method: 'DELETE' });
  };
  /**
   * @summary 获取所有射频信号参数列表
   */
  const getAllSignalParams = () => {
    return customInstance<ResultListSignalParamsVO>({ url: `/api/signal/list`, method: 'GET' });
  };
  return { recognizeSignalParams, getSignalParamsById, deleteSignalParams, getAllSignalParams };
};
export type RecognizeSignalParamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['recognizeSignalParams']>>
>;
export type GetSignalParamsByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['getSignalParamsById']>>
>;
export type DeleteSignalParamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['deleteSignalParams']>>
>;
export type GetAllSignalParamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRfSignalParams>['getAllSignalParams']>>
>;
